// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

import {IVerifier} from "../chain-interfaces/IVerifier.sol";
import {IZiskVerifier} from "../chain-interfaces/IZiskVerifier.sol";
import {IZiskSnarkPlonkVerifier} from "../chain-interfaces/IZiskSnarkPlonkVerifier.sol";
import {PUBLIC_INPUT_SHIFT} from "../../common/Config.sol";

/// @title ZiSK Verifier
/// @author Matter Labs
/// @custom:security-contact security@matterlabs.dev
/// @notice Verifies the aggregated ZiSK SNARK for a batch range on behalf of
///         MultiProofVerifier (registered as its range verifier).
/// @dev The 576-byte ZiSK public values are RECONSTRUCTED on-chain from this
///      contract's pinned VKs and the batch public inputs — nothing about the
///      state transition is read from the submitted proof, which carries only
///      the SNARK itself. MultiProofVerifier strips the proof header
///      (type+version, previous_hash, N, airbender_proof) before calling this
///      contract, so _proof is the 24-word ZiSK SNARK (768 bytes) and
///      _publicInputs are the batch public inputs of the range.
///
/// @dev Two guest programs take part in one aggregated proof. The inner
///      state-transition guest proves each batch. The aggregator guest ingests
///      those inner proofs and outputs the aggregated public values. The two
///      programs are different ELFs, so they have different programVKs. This
///      contract pins both. It uses each pin in one place only: the inner pin
///      in the binding digest, the aggregator pin in public-values bytes
///      [0..32].
///
/// @dev Implements IZiskVerifier so the pinned wire-form VKs can be read back
///      off-chain (e.g. the server cross-checks them against the guest VKs).
///
/// @dev Generated by `cargo run -- --variant zisk` in `tools/verifier-gen/`.
///      VK hash: 0x8fc266228091187640e69d426031adf6d8b6f2fe799a1f4fad7a43bb9c4a03c1
contract ZiskVerifier is IZiskVerifier {
    /// @notice The snarkJS-generated Plonk verifier for the ZiSK vadcop-final
    ///         wrap. Regenerated with the circuit, so it is deployed as a
    ///         standalone contract and referenced by address; see
    ///         `verifiers/README.md` for the generation and deployment flow.
    IZiskSnarkPlonkVerifier public immutable PLONK_VERIFIER;

    error ProofTooShort();

    constructor(IZiskSnarkPlonkVerifier _plonkVerifier) {
        PLONK_VERIFIER = _plonkVerifier;
    }

    /// @notice programVK of the inner state-transition guest ELF.
    /// Derived from the ROM Merkle root of that ELF. The reconstruction uses
    /// it in the binding digest only.
    /// @dev STALE: a placeholder, not a guest ELF root. The real limbs come
    /// from the `rotate-program-vks` dispatch in the ZiSK repository. Put them
    /// into the ZiSK VK JSON and regenerate this contract.
    uint64 private constant _INNER_PROGRAM_VK_0 = 13700430501868844200;
    uint64 private constant _INNER_PROGRAM_VK_1 = 15096809239806032041;
    uint64 private constant _INNER_PROGRAM_VK_2 = 12859342089998199634;
    uint64 private constant _INNER_PROGRAM_VK_3 = 9860071608042129445;
    /// @notice programVK of the aggregator guest ELF.
    /// Derived from the ROM Merkle root of that ELF. The aggregated proof
    /// attests to this program, so the reconstruction uses it in public-values
    /// bytes [0..32] only.
    /// @dev STALE: a placeholder, not a guest ELF root. The real limbs come
    /// from the `rotate-program-vks` dispatch in the ZiSK repository. Put them
    /// into the ZiSK VK JSON and regenerate this contract.
    uint64 private constant _AGGREGATOR_PROGRAM_VK_0 = 12432157590653728692;
    uint64 private constant _AGGREGATOR_PROGRAM_VK_1 = 12050317199529546573;
    uint64 private constant _AGGREGATOR_PROGRAM_VK_2 = 4997395890756632183;
    uint64 private constant _AGGREGATOR_PROGRAM_VK_3 = 12023935818373595804;
    /// @notice ZiSK vadcop final root commitment: the recursive-setup constant
    /// of the ZiSK release. One cargo-zisk setup produces both the inner proofs
    /// and the aggregated proof, so a single pin serves both. The
    /// reconstruction uses it in the binding digest and in public-values bytes
    /// [544..576].
    uint64 private constant _ROOT_CV_ADCOP_FINAL_0 = 6218392583875695404;
    uint64 private constant _ROOT_CV_ADCOP_FINAL_1 = 9353885302538021251;
    uint64 private constant _ROOT_CV_ADCOP_FINAL_2 = 8280779842059074605;
    uint64 private constant _ROOT_CV_ADCOP_FINAL_3 = 10684020678174455855;
    /// @notice BN254 scalar field modulus.
    uint256 private constant _RFIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @notice Byte length of the ZiSK public-values preimage:
    /// aggregatorProgramVK(32) || guest publics(512) || rootCVadcopFinal(32).
    uint256 private constant _PUBLIC_VALUES_BYTES = 576;

    /// @notice Hash over the three pins above, in the order inner programVK,
    /// aggregator programVK, vadcop-final root. The server derives the ZiSK
    /// verification key hash of the protocol version the same way, so a
    /// rotation of any pin is visible on both sides.
    /// @dev STALE: derived from a placeholder programVK pin, so it names no
    /// deployed guest. It rotates with the pin.
    bytes32 private constant _VK_HASH = 0x8fc266228091187640e69d426031adf6d8b6f2fe799a1f4fad7a43bb9c4a03c1;

    /// @inheritdoc IZiskVerifier
    function innerProgramVK() public pure override returns (bytes32) {
        return
            bytes32(
                (uint256(_INNER_PROGRAM_VK_0) << 192) |
                    (uint256(_INNER_PROGRAM_VK_1) << 128) |
                    (uint256(_INNER_PROGRAM_VK_2) << 64) |
                    uint256(_INNER_PROGRAM_VK_3)
            );
    }

    /// @inheritdoc IZiskVerifier
    function aggregatorProgramVK() public pure override returns (bytes32) {
        return
            bytes32(
                (uint256(_AGGREGATOR_PROGRAM_VK_0) << 192) |
                    (uint256(_AGGREGATOR_PROGRAM_VK_1) << 128) |
                    (uint256(_AGGREGATOR_PROGRAM_VK_2) << 64) |
                    uint256(_AGGREGATOR_PROGRAM_VK_3)
            );
    }

    /// @inheritdoc IZiskVerifier
    function rootCVadcopFinal() public pure override returns (bytes32) {
        return
            bytes32(
                (uint256(_ROOT_CV_ADCOP_FINAL_0) << 192) |
                    (uint256(_ROOT_CV_ADCOP_FINAL_1) << 128) |
                    (uint256(_ROOT_CV_ADCOP_FINAL_2) << 64) |
                    uint256(_ROOT_CV_ADCOP_FINAL_3)
            );
    }

    /// @inheritdoc IVerifier
    /// @param _publicInputs The batch public inputs of the range, as L1
    ///        consumes them. The self-contained (seed-0) chain over them is the
    ///        value the aggregator guest committed to.
    /// @param _proof The 24-word (768-byte) BN254 PLONK SNARK proof. Nothing
    ///        else is read from it: the public values are reconstructed below.
    function verify(uint256[] calldata _publicInputs, uint256[] calldata _proof) external view override returns (bool) {
        if (_proof.length < 24) revert ProofTooShort();

        // Extract the 24-element ZiSK SNARK proof.
        uint256[24] memory ziskProof;
        for (uint256 i = 0; i < 24; ++i) {
            ziskProof[i] = _proof[i];
        }

        // Reconstruct the 576-byte ZiSK public-values preimage the aggregated
        // proof commits to — entirely from this contract's pinned VKs and the
        // batch public inputs, never from the submitted proof. Wire layout
        // (matching the aggregator guest's output region):
        //   [0..32]    aggregatorProgramVK (this contract's pin)
        //   [32..544]  guest publics       64 little-endian u64 slots
        //   [544..576] rootCVadcopFinal    (this contract's pin)
        // A guest public holds a 32-bit value, so each slot is four significant
        // bytes then four zero pad bytes. The aggregator guest writes the
        // binding digest keccak256(innerProgramVK || rootCVadcopFinal ||
        // chainedPI) into the first eight slots and leaves the rest zero:
        //   [32..96]   digest, four bytes per slot, eight slots
        //   [96..544]  zero (448 bytes)
        // where chainedPI is the SELF-CONTAINED (seed-0) ZKsync OS hash chain
        // over the batch public inputs.
        //
        // The aggregator guest builds the digest from the VKs of the inner
        // proofs it ingests. Therefore the digest carries the INNER pin, and
        // the wire carries the AGGREGATOR pin. The two pins identify different
        // ELFs. Do not exchange them.
        //
        // Because the preimage is built from the contract's own pins, the
        // former pinned-VK checks are inherent: a proof for a different guest
        // program or SNARK circuit can not match. Because the digest is built
        // from the re-derived chainedPI, the cross-proof binding is inherent
        // too: a proof attesting to a different batch range reconstructs a
        // different signal and fails the pairing below.
        bytes32 aggregatorVk = aggregatorProgramVK();
        bytes32 rootC = rootCVadcopFinal();
        bytes32 digest = keccak256(
            abi.encodePacked(innerProgramVK(), rootC, bytes32(_selfContainedChain(_publicInputs)))
        );

        bytes32 digestSlots0 = _digestPublicSlots(uint128(uint256(digest) >> 128));
        bytes32 digestSlots1 = _digestPublicSlots(uint128(uint256(digest)));

        bytes memory publicValues = new bytes(_PUBLIC_VALUES_BYTES);
        assembly {
            mstore(add(publicValues, 32), aggregatorVk) // [0..32]   aggregatorProgramVK
            mstore(add(publicValues, 64), digestSlots0) // [32..64]  digest slots 0-3
            mstore(add(publicValues, 96), digestSlots1) // [64..96]  digest slots 4-7
            // [96..544] left zero by the allocation above
            mstore(add(publicValues, 576), rootC) // [544..576] rootCVadcopFinal
        }

        // The circuit's single public signal: sha256(publicValues) % RFIELD.
        uint256 publicValuesDigest = uint256(sha256(publicValues)) % _RFIELD;

        return PLONK_VERIFIER.verifyProof(ziskProof, [publicValuesDigest]);
    }

    /// @inheritdoc IVerifier
    function verificationKeyHash() external pure override returns (bytes32) {
        return _VK_HASH;
    }

    /// @dev The self-contained (seed-0) ZKsync OS hash chain over the batch
    ///      public inputs: the value the aggregated ZiSK range proof commits
    ///      to. One keccak256 over the concatenated untruncated inputs,
    ///      shifted once, which is the rule
    ///      `ZKsyncOSVerifier.computeZKsyncOSHash` applies from seed 0 and the
    ///      aggregator guest applies in-guest. An aggregated range always opens
    ///      its own chain, independent of the Airbender previous_hash.
    function _selfContainedChain(uint256[] calldata _publicInputs) private pure returns (uint256 result) {
        // One batch carries its own public input, so the fold has nothing to
        // hash. Hashing it anyway would part company with the aggregator guest,
        // which reaches the same value through the same rule.
        result = _publicInputs.length == 1 ? _publicInputs[0] : uint256(keccak256(abi.encodePacked(_publicInputs)));
        result = result >> PUBLIC_INPUT_SHIFT;
    }

    /// @dev The four guest-public slots that carry `_digestHalf`, sixteen
    ///      digest bytes read as four 4-byte groups. A slot holds one group in
    ///      its four significant bytes and four zero pad bytes, so the four
    ///      slots are one 32-byte word of the public values. Call it on the
    ///      high half for word [32..64] and on the low half for word [64..96].
    function _digestPublicSlots(uint128 _digestHalf) private pure returns (bytes32 slots) {
        uint256 packed;
        for (uint256 i = 0; i < 4; ++i) {
            packed |= uint256(uint32(_digestHalf >> (96 - i * 32))) << (224 - i * 64);
        }
        slots = bytes32(packed);
    }
}
