// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

import {IVerifier} from "../chain-interfaces/IVerifier.sol";
import {IZiskVerifier} from "../chain-interfaces/IZiskVerifier.sol";
import {IZiskSnarkPlonkVerifier} from "../chain-interfaces/IZiskSnarkPlonkVerifier.sol";
import {PUBLIC_INPUT_SHIFT} from "../../common/Config.sol";

/// @title ZiSK Verifier
/// @author Matter Labs
/// @custom:security-contact security@matterlabs.dev
/// @notice Verifies the aggregated ZiSK SNARK for a batch range on behalf of
///         MultiProofVerifier (registered as its range verifier).
/// @dev The 320-byte ZiSK public values are RECONSTRUCTED on-chain from this
///      contract's pinned VKs and the batch public inputs — nothing about the
///      state transition is read from the submitted proof, which carries only
///      the SNARK itself. MultiProofVerifier strips the proof header
///      (type+version, previous_hash, N, airbender_proof) before calling this
///      contract, so _proof is the 24-word ZiSK SNARK (768 bytes) and
///      _publicInputs are the batch public inputs of the range.
///
/// @dev Two guest programs take part in one aggregated proof. The inner
///      state-transition guest proves each batch. The aggregator guest ingests
///      those inner proofs and outputs the aggregated public values. The two
///      programs are different ELFs, so they have different programVKs. This
///      contract pins both. It uses each pin in one place only: the inner pin
///      in the binding digest, the aggregator pin in public-values bytes
///      [0..32].
///
/// @dev Implements IZiskVerifier so the pinned wire-form VKs can be read back
///      off-chain (e.g. the server cross-checks them against the guest VKs).
///
/// @dev Generated by `cargo run -- --variant zisk` in `tools/verifier-gen/`.
///      VK hash: 0x9d04cf648d751264abba6492119b5b141daab63ed501d24813919a939512a999
contract ZiskVerifier is IZiskVerifier {
    /// @notice The snarkJS-generated Plonk verifier for the ZiSK vadcop-final
    ///         wrap. Regenerated with the circuit, so it is deployed as a
    ///         standalone contract and referenced by address; see
    ///         `verifiers/README.md` for the generation and deployment flow.
    IZiskSnarkPlonkVerifier public immutable PLONK_VERIFIER;

    error ProofTooShort();

    constructor(IZiskSnarkPlonkVerifier _plonkVerifier) {
        PLONK_VERIFIER = _plonkVerifier;
    }

    /// @notice programVK of the inner state-transition guest ELF.
    /// Derived from the ROM Merkle root of that ELF. The reconstruction uses
    /// it in the binding digest only.
    uint64 private constant _INNER_PROGRAM_VK_0 = 9324920540708014748;
    uint64 private constant _INNER_PROGRAM_VK_1 = 8809135547294377884;
    uint64 private constant _INNER_PROGRAM_VK_2 = 14330412989579270068;
    uint64 private constant _INNER_PROGRAM_VK_3 = 18349445223923896448;
    /// @notice programVK of the aggregator guest ELF.
    /// Derived from the ROM Merkle root of that ELF. The aggregated proof
    /// attests to this program, so the reconstruction uses it in public-values
    /// bytes [0..32] only.
    uint64 private constant _AGGREGATOR_PROGRAM_VK_0 = 17765460705594893175;
    uint64 private constant _AGGREGATOR_PROGRAM_VK_1 = 12644773086732340805;
    uint64 private constant _AGGREGATOR_PROGRAM_VK_2 = 13570135610615888618;
    uint64 private constant _AGGREGATOR_PROGRAM_VK_3 = 5218006920068642616;
    /// @notice ZiSK vadcop final root commitment: the recursive-setup constant
    /// of the ZiSK release. One cargo-zisk setup produces both the inner proofs
    /// and the aggregated proof, so a single pin serves both. The
    /// reconstruction uses it in the binding digest and in public-values bytes
    /// [288..320].
    uint64 private constant _ROOT_CV_ADCOP_FINAL_0 = 14927797345724729265;
    uint64 private constant _ROOT_CV_ADCOP_FINAL_1 = 4864849507313518298;
    uint64 private constant _ROOT_CV_ADCOP_FINAL_2 = 8191503835439821522;
    uint64 private constant _ROOT_CV_ADCOP_FINAL_3 = 363572921032801149;
    /// @notice BN254 scalar field modulus.
    uint256 private constant _RFIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @notice Hash over the three pins above, in the order inner programVK,
    /// aggregator programVK, vadcop-final root. The server derives the ZiSK
    /// verification key hash of the protocol version the same way, so a
    /// rotation of any pin is visible on both sides.
    bytes32 private constant _VK_HASH = 0x9d04cf648d751264abba6492119b5b141daab63ed501d24813919a939512a999;

    /// @inheritdoc IZiskVerifier
    function innerProgramVK() public pure override returns (bytes32) {
        return
            bytes32(
                (uint256(_INNER_PROGRAM_VK_0) << 192) |
                    (uint256(_INNER_PROGRAM_VK_1) << 128) |
                    (uint256(_INNER_PROGRAM_VK_2) << 64) |
                    uint256(_INNER_PROGRAM_VK_3)
            );
    }

    /// @inheritdoc IZiskVerifier
    function aggregatorProgramVK() public pure override returns (bytes32) {
        return
            bytes32(
                (uint256(_AGGREGATOR_PROGRAM_VK_0) << 192) |
                    (uint256(_AGGREGATOR_PROGRAM_VK_1) << 128) |
                    (uint256(_AGGREGATOR_PROGRAM_VK_2) << 64) |
                    uint256(_AGGREGATOR_PROGRAM_VK_3)
            );
    }

    /// @inheritdoc IZiskVerifier
    function rootCVadcopFinal() public pure override returns (bytes32) {
        return
            bytes32(
                (uint256(_ROOT_CV_ADCOP_FINAL_0) << 192) |
                    (uint256(_ROOT_CV_ADCOP_FINAL_1) << 128) |
                    (uint256(_ROOT_CV_ADCOP_FINAL_2) << 64) |
                    uint256(_ROOT_CV_ADCOP_FINAL_3)
            );
    }

    /// @inheritdoc IVerifier
    /// @param _publicInputs The batch public inputs of the range, as L1
    ///        consumes them. The self-contained (seed-0) chain over them is the
    ///        value the aggregator guest committed to.
    /// @param _proof The 24-word (768-byte) BN254 PLONK SNARK proof. Nothing
    ///        else is read from it: the public values are reconstructed below.
    function verify(uint256[] calldata _publicInputs, uint256[] calldata _proof) external view override returns (bool) {
        if (_proof.length < 24) revert ProofTooShort();

        // Extract the 24-element ZiSK SNARK proof.
        uint256[24] memory ziskProof;
        for (uint256 i = 0; i < 24; ++i) {
            ziskProof[i] = _proof[i];
        }

        // Reconstruct the 320-byte ZiSK public-values preimage the aggregated
        // proof commits to — entirely from this contract's pinned VKs and the
        // batch public inputs, never from the submitted proof. Wire layout
        // (matching the aggregator guest's output region):
        //   [0..32]    aggregatorProgramVK (this contract's pin)
        //   [32..64]   digest              keccak256(innerProgramVK || rootCVadcopFinal || chainedPI)
        //   [64..288]  zero (224 bytes)
        //   [288..320] rootCVadcopFinal    (this contract's pin)
        // where chainedPI is the SELF-CONTAINED (seed-0) ZKsync OS hash chain
        // over the batch public inputs.
        //
        // The aggregator guest builds the digest from the VKs of the inner
        // proofs it ingests. Therefore the digest carries the INNER pin, and
        // the wire carries the AGGREGATOR pin. The two pins identify different
        // ELFs. Do not exchange them.
        //
        // Because the preimage is built from the contract's own pins, the
        // former pinned-VK checks are inherent: a proof for a different guest
        // program or SNARK circuit can not match. Because the digest is built
        // from the re-derived chainedPI, the cross-proof binding is inherent
        // too: a proof attesting to a different batch range reconstructs a
        // different signal and fails the pairing below.
        bytes32 aggregatorVk = aggregatorProgramVK();
        bytes32 rootC = rootCVadcopFinal();
        bytes32 digest = keccak256(
            abi.encodePacked(innerProgramVK(), rootC, bytes32(_selfContainedChain(_publicInputs)))
        );

        bytes memory publicValues = new bytes(320);
        assembly {
            mstore(add(publicValues, 32), aggregatorVk) // [0..32]   aggregatorProgramVK
            mstore(add(publicValues, 64), digest) // [32..64]  binding digest
            // [64..288] left zero by `new bytes(320)`
            mstore(add(publicValues, 320), rootC) // [288..320] rootCVadcopFinal
        }

        // The circuit's single public signal: sha256(publicValues) % RFIELD.
        uint256 publicValuesDigest = uint256(sha256(publicValues)) % _RFIELD;

        return PLONK_VERIFIER.verifyProof(ziskProof, [publicValuesDigest]);
    }

    /// @inheritdoc IVerifier
    function verificationKeyHash() external pure override returns (bytes32) {
        return _VK_HASH;
    }

    /// @dev The self-contained (seed-0) ZKsync OS hash chain over the batch
    ///      public inputs: the value the aggregated ZiSK range proof commits
    ///      to. One keccak256 over the concatenated untruncated inputs,
    ///      shifted once, which is the rule
    ///      `ZKsyncOSVerifier.computeZKsyncOSHash` applies from seed 0 and the
    ///      aggregator guest applies in-guest. An aggregated range always opens
    ///      its own chain, independent of the Airbender previous_hash.
    function _selfContainedChain(uint256[] calldata _publicInputs) private pure returns (uint256 result) {
        // One batch carries its own public input, so the fold has nothing to
        // hash. Hashing it anyway would part company with the aggregator guest,
        // which reaches the same value through the same rule.
        result = _publicInputs.length == 1 ? _publicInputs[0] : uint256(keccak256(abi.encodePacked(_publicInputs)));
        result = result >> PUBLIC_INPUT_SHIFT;
    }
}
