#!/bin/sh

CYAN='\033[0;36m'
NC='\033[0m' # No Color
RED='\033[0;31m'

# Checking that the code is linted and formatted in the given directory provided in the first argument
function check_lint {
    cd $1
    if ! yarn lint:check; then
        echo "${RED}Push error! Cannot push unlinted code!${NC}"
        echo "Lint errors found in the ${CYAN}$(pwd)${NC} directory."
        echo "Please lint the code via ${CYAN}cd $1 && yarn lint:fix${NC} and/or fix the errors manually!"
        exit 1
    fi
    cd ..
}

check_lint "ethereum"
check_lint "zksync"