/**
 * gen-registry: deterministically generates constants-in-bytecode upgrade registry contracts
 * from an audited manifest JSON.
 *
 *   manifest.json (audited) -> ts-node scripts/gen-registry.ts <manifest> <outDir> -> *.sol -> forge build
 *
 * No human hand-writes a constant in the generated files; reproducing the same source from the
 * same manifest is what auditors verify. See docs/upgrade-streamlining-proposal.md.
 *
 * Usage: ts-node scripts/gen-registry.ts <manifest.json> <output-dir> [--interface-path <path>]
 *   --interface-path: import prefix for the registry interfaces, default
 *                     "contracts/upgrades/registry".
 */

import * as fs from "fs";
import * as path from "path";

interface CoreContractEntry {
  proxy: string;
  implOld?: string;
  implNew?: string;
  implNewCodehash?: string;
}

interface FacetEntry {
  name: string;
  selectors: string[];
}

interface L2ForceDeployment {
  contract: string;
  upgradeType: "EraForceDeployment" | "ZKsyncOSSystemProxyUpgrade" | "ZKsyncOSUnsafeForceDeployment";
  deployedBytecodeInfo: string;
  newAddress: string;
  bytecodeHash: string;
}

interface CTMManifest {
  name: string;
  isZKsyncOS: boolean;
  ctmProxy: string;
  verifierOld: string;
  verifierNew: string;
  contracts: Record<string, { old?: string; new?: string; newCodehash?: string }>;
  facets: { old: FacetEntry[]; new: FacetEntry[] };
  facetFreezability: Record<string, boolean>;
  l2: {
    forceDeployments: L2ForceDeployment[];
    delegateTo: string;
    delegateCalldata: string;
    factoryDepHashes: string[];
    baseSystemContracts: { bootloader: string; defaultAccount: string; evmEmulator: string };
    fixedForceDeploymentsData: string;
    chainCreationInitCalldata: string;
  };
  genesis: {
    genesisUpgrade: string;
    batchHash: string;
    batchCommitment: string;
    indexRepeatedStorageChanges: number;
  };
}

interface Manifest {
  tag: string;
  oldVersion: string;
  newVersion: string;
  core: {
    proxyAdmin: string;
    ctmRegistries: { era: string; zksyncOS: string };
    contracts: Record<string, CoreContractEntry>;
  };
  ctms: CTMManifest[];
}

const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000";

function packSemVer(version: string): bigint {
  const parts = version.split(".").map((p) => BigInt(p));
  if (parts.length !== 3) throw new Error(`invalid semver: ${version}`);
  const [major, minor, patch] = parts;
  // BigInt literals require ES2020; construct the shift amounts explicitly instead.
  return (major << BigInt(64)) | (minor << BigInt(32)) | patch;
}

function checksum(addr: string): string {
  // Addresses are emitted lowercase; Solidity accepts 40-hex-digit literals only when EIP-55
  // checksummed. To stay dependency-free, prepend `00` so the literal is a plain number and
  // cast it back down to an address.
  return `address(uint160(0x00${addr.slice(2).toLowerCase()}))`;
}

function header(contractName: string, manifestPath: string, ifacePath: string, imports: string[]): string {
  return `// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from ${path.basename(manifestPath)}.
// Every value below is a compile-time constant: deploying this contract IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

${imports.map((i) => `import {${i}} from "${ifacePath}/${i.startsWith("I") ? i : "ContractIdentifiers"}.sol";`).join("\n")}
`;
}

function generateCore(m: Manifest, manifestPath: string, ifacePath: string): string {
  const name = `CoreRegistry${m.tag}`;
  const oldV = packSemVer(m.oldVersion);
  const newV = packSemVer(m.newVersion);
  const entries = Object.entries(m.core.contracts);

  const proxyBranches = entries
    .map(([c, e]) => `        if (_contract == EcosystemContract.${c}) return ${checksum(e.proxy)};`)
    .join("\n");

  const implBranches = entries
    .flatMap(([c, e]) => {
      const out: string[] = [];
      if (e.implOld)
        out.push(
          `        if (_contract == EcosystemContract.${c} && _protocolVersion == OLD_PROTOCOL_VERSION) return ${checksum(e.implOld)};`
        );
      if (e.implNew)
        out.push(
          `        if (_contract == EcosystemContract.${c} && _protocolVersion == NEW_PROTOCOL_VERSION) return ${checksum(e.implNew)};`
        );
      return out;
    })
    .join("\n");

  const listBody = entries.map(([c], i) => `        list[${i}] = EcosystemContract.${c};`).join("\n");

  const verifyChecks = entries
    .filter(([, e]) => e.implNew && e.implNewCodehash)
    .map(([, e]) => `        if (${checksum(e.implNew!)}.codehash != ${e.implNewCodehash}) return false;`)
    .join("\n");

  return `${header(name, manifestPath, ifacePath, ["ICoreRegistry", "EcosystemContract"])}
contract ${name} is ICoreRegistry {
    uint256 internal constant OLD_PROTOCOL_VERSION = ${oldV}; // ${m.oldVersion}
    uint256 internal constant NEW_PROTOCOL_VERSION = ${newV}; // ${m.newVersion}

    error RegistryUnknownKey();

    function oldProtocolVersion() external pure returns (uint256) {
        return OLD_PROTOCOL_VERSION;
    }

    function newProtocolVersion() external pure returns (uint256) {
        return NEW_PROTOCOL_VERSION;
    }

    function proxyAddress(EcosystemContract _contract) external pure returns (address) {
${proxyBranches}
        revert RegistryUnknownKey();
    }

    function implAddress(EcosystemContract _contract, uint256 _protocolVersion) external pure returns (address) {
${implBranches}
        if (_protocolVersion == OLD_PROTOCOL_VERSION || _protocolVersion == NEW_PROTOCOL_VERSION) return address(0);
        revert RegistryUnknownKey();
    }

    function ecosystemContractList() external pure returns (EcosystemContract[] memory list) {
        list = new EcosystemContract[](${entries.length});
${listBody}
    }

    function proxyAdmin() external pure returns (address) {
        return ${checksum(m.core.proxyAdmin)};
    }

    function ctmRegistry(bool _isZKsyncOS) external pure returns (address) {
        return _isZKsyncOS ? ${checksum(m.core.ctmRegistries.zksyncOS)} : ${checksum(m.core.ctmRegistries.era)};
    }

    function verifyAll() external view returns (bool) {
${verifyChecks || "        // No codehashes pinned in the manifest."}
        return true;
    }
}
`;
}

function facetListBody(facets: FacetEntry[]): string {
  return facets.map((f, i) => `        list[${i}] = CTMContract.${f.name};`).join("\n");
}

function selectorBranches(facets: FacetEntry[], versionConst: string): string {
  return facets
    .map((f) => {
      const fill = f.selectors.map((s, i) => `            selectors[${i}] = bytes4(${s});`).join("\n");
      return `        if (_facet == CTMContract.${f.name} && _protocolVersion == ${versionConst}) {
            selectors = new bytes4[](${f.selectors.length});
${fill}
            return selectors;
        }`;
    })
    .join("\n");
}

function generateCTM(m: Manifest, ctm: CTMManifest, manifestPath: string, ifacePath: string): string {
  const name = `${ctm.name}CTMRegistry${m.tag}`;
  const oldV = packSemVer(m.oldVersion);
  const newV = packSemVer(m.newVersion);

  const addressBranches = Object.entries(ctm.contracts)
    .flatMap(([c, e]) => {
      const out: string[] = [];
      if (e.old)
        out.push(
          `        if (_contract == CTMContract.${c} && _protocolVersion == OLD_PROTOCOL_VERSION) return ${checksum(e.old)};`
        );
      if (e.new)
        out.push(
          `        if (_contract == CTMContract.${c} && _protocolVersion == NEW_PROTOCOL_VERSION) return ${checksum(e.new)};`
        );
      return out;
    })
    .join("\n");

  const freezableBranches = Object.entries(ctm.facetFreezability)
    .map(([f, freezable]) => `        if (_facet == CTMContract.${f}) return ${freezable};`)
    .join("\n");

  const fds = ctm.l2.forceDeployments;
  const fdListBody = fds.map((d, i) => `        list[${i}] = CoreContract.${d.contract};`).join("\n");
  const fdBranches = fds
    .map(
      (d) => `        if (_contract == CoreContract.${d.contract} && _protocolVersion == NEW_PROTOCOL_VERSION) {
            return IComplexUpgrader.UniversalContractUpgradeInfo({
                upgradeType: IComplexUpgrader.ContractUpgradeType.${d.upgradeType},
                deployedBytecodeInfo: hex"${d.deployedBytecodeInfo.replace(/^0x/, "")}",
                newAddress: ${checksum(d.newAddress)}
            });
        }`
    )
    .join("\n");
  const hashBranches = fds
    .map(
      (d) =>
        `        if (_contract == CoreContract.${d.contract} && _protocolVersion == NEW_PROTOCOL_VERSION) return ${d.bytecodeHash};`
    )
    .join("\n");

  const factoryDeps = ctm.l2.factoryDepHashes.map((h, i) => `        hashes[${i}] = uint256(${h});`).join("\n");

  const verifyChecks = Object.entries(ctm.contracts)
    .filter(([, e]) => e.new && e.newCodehash)
    .map(([, e]) => `        if (${checksum(e.new!)}.codehash != ${e.newCodehash}) return false;`)
    .join("\n");

  return `${header(name, manifestPath, ifacePath, ["ICTMRegistry", "CoreContract"])}
import {CTMContract} from "${ifacePath}/ContractIdentifiers.sol";
import {IComplexUpgrader} from "contracts/state-transition/l2-deps/IComplexUpgrader.sol";

contract ${name} is ICTMRegistry {
    uint256 internal constant OLD_PROTOCOL_VERSION = ${oldV}; // ${m.oldVersion}
    uint256 internal constant NEW_PROTOCOL_VERSION = ${newV}; // ${m.newVersion}

    error RegistryUnknownKey();

    function isZKsyncOS() external pure returns (bool) {
        return ${ctm.isZKsyncOS};
    }

    function oldProtocolVersion() external pure returns (uint256) {
        return OLD_PROTOCOL_VERSION;
    }

    function newProtocolVersion() external pure returns (uint256) {
        return NEW_PROTOCOL_VERSION;
    }

    function ctmProxy() external pure returns (address) {
        return ${checksum(ctm.ctmProxy)};
    }

    function ctmAddress(CTMContract _contract, uint256 _protocolVersion) external pure returns (address) {
${addressBranches}
        if (_protocolVersion == OLD_PROTOCOL_VERSION || _protocolVersion == NEW_PROTOCOL_VERSION) return address(0);
        revert RegistryUnknownKey();
    }

    function verifier(uint256 _protocolVersion) external pure returns (address) {
        if (_protocolVersion == OLD_PROTOCOL_VERSION) return ${checksum(ctm.verifierOld)};
        if (_protocolVersion == NEW_PROTOCOL_VERSION) return ${checksum(ctm.verifierNew)};
        revert RegistryUnknownKey();
    }

    function facetList(uint256 _protocolVersion) external pure returns (CTMContract[] memory list) {
        if (_protocolVersion == OLD_PROTOCOL_VERSION) {
            list = new CTMContract[](${ctm.facets.old.length});
${facetListBody(ctm.facets.old).replace(/list\[/g, "list[")}
            return list;
        }
        if (_protocolVersion == NEW_PROTOCOL_VERSION) {
            list = new CTMContract[](${ctm.facets.new.length});
${facetListBody(ctm.facets.new)}
            return list;
        }
        revert RegistryUnknownKey();
    }

    function facetSelectors(CTMContract _facet, uint256 _protocolVersion) external pure returns (bytes4[] memory selectors) {
${selectorBranches(ctm.facets.old, "OLD_PROTOCOL_VERSION")}
${selectorBranches(ctm.facets.new, "NEW_PROTOCOL_VERSION")}
        revert RegistryUnknownKey();
    }

    function facetIsFreezable(CTMContract _facet) external pure returns (bool) {
${freezableBranches}
        revert RegistryUnknownKey();
    }

    function l2ForceDeployList(uint256 _protocolVersion) external pure returns (CoreContract[] memory list) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        list = new CoreContract[](${fds.length});
${fdListBody}
    }

    function l2ForceDeployment(
        CoreContract _contract,
        uint256 _protocolVersion
    ) external pure returns (IComplexUpgrader.UniversalContractUpgradeInfo memory) {
${fdBranches}
        revert RegistryUnknownKey();
    }

    function l2BytecodeHash(CoreContract _contract, uint256 _protocolVersion) external pure returns (bytes32) {
${hashBranches}
        if (_protocolVersion == OLD_PROTOCOL_VERSION || _protocolVersion == NEW_PROTOCOL_VERSION) return bytes32(0);
        revert RegistryUnknownKey();
    }

    function l2UpgradeDelegate(
        uint256 _protocolVersion
    ) external pure returns (address delegateTo, bytes memory delegateCalldata) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return (${checksum(ctm.l2.delegateTo)}, hex"${ctm.l2.delegateCalldata.replace(/^0x/, "")}");
    }

    function factoryDepHashes(uint256 _protocolVersion) external pure returns (uint256[] memory hashes) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        hashes = new uint256[](${ctm.l2.factoryDepHashes.length});
${factoryDeps}
    }

    function baseSystemContractHashes(
        uint256 _protocolVersion
    ) external pure returns (bytes32 bootloaderHash, bytes32 defaultAccountHash, bytes32 evmEmulatorHash) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return (
            ${ctm.l2.baseSystemContracts.bootloader},
            ${ctm.l2.baseSystemContracts.defaultAccount},
            ${ctm.l2.baseSystemContracts.evmEmulator}
        );
    }

    function fixedForceDeploymentsData(uint256 _protocolVersion) external pure returns (bytes memory) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return hex"${ctm.l2.fixedForceDeploymentsData.replace(/^0x/, "")}";
    }

    function chainCreationInitCalldata(uint256 _protocolVersion) external pure returns (bytes memory) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return hex"${ctm.l2.chainCreationInitCalldata.replace(/^0x/, "")}";
    }

    function genesisParams(
        uint256 _protocolVersion
    )
        external
        pure
        returns (
            address genesisUpgrade,
            bytes32 genesisBatchHash,
            bytes32 genesisBatchCommitment,
            uint64 genesisIndexRepeatedStorageChanges
        )
    {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return (
            ${checksum(ctm.genesis.genesisUpgrade)},
            ${ctm.genesis.batchHash},
            ${ctm.genesis.batchCommitment},
            ${ctm.genesis.indexRepeatedStorageChanges}
        );
    }

    function verifyAll() external view returns (bool) {
${verifyChecks || "        // No codehashes pinned in the manifest."}
        return true;
    }
}
`;
}

function main() {
  const [manifestPath, outDir] = process.argv.slice(2);
  if (!manifestPath || !outDir) {
    console.error("Usage: ts-node scripts/gen-registry.ts <manifest.json> <output-dir> [--interface-path <p>]");
    process.exit(1);
  }
  const ifaceFlag = process.argv.indexOf("--interface-path");
  const ifacePath = ifaceFlag > 0 ? process.argv[ifaceFlag + 1] : "contracts/upgrades/registry";

  const manifest: Manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
  fs.mkdirSync(outDir, { recursive: true });

  const coreFile = path.join(outDir, `CoreRegistry${manifest.tag}.sol`);
  fs.writeFileSync(coreFile, generateCore(manifest, manifestPath, ifacePath));
  console.log(`generated ${coreFile}`);

  for (const ctm of manifest.ctms) {
    const ctmFile = path.join(outDir, `${ctm.name}CTMRegistry${manifest.tag}.sol`);
    fs.writeFileSync(ctmFile, generateCTM(manifest, ctm, manifestPath, ifacePath));
    console.log(`generated ${ctmFile}`);
  }
}

main();
