/**
 * gen-registry: deterministically generates constants-in-bytecode upgrade registry contracts
 * from an audited manifest JSON.
 *
 *   manifest.json (audited) -> ts-node scripts/gen-registry.ts <manifest> <outDir> -> *.sol -> forge build
 *
 * Generated output is DATA ONLY: per registry, a `<Name>Data.sol` library of typed rows plus a
 * thin `<Name>.sol` shim wiring it into the fixed, hand-written logic base
 * (contracts/upgrades/registry/CTMRegistryBase.sol / CoreRegistryBase.sol). Lookup logic, version
 * gating and revert semantics are audited once in the bases; the per-upgrade audit diff is rows.
 * Library functions are internal and inlined at compile time, so each deployed registry remains a
 * single contract whose EXTCODEHASH commits to every value.
 *
 * No human hand-writes a constant in the generated files; reproducing the same source from the
 * same manifest is what auditors verify. See docs/upgrade-streamlining-proposal.md.
 *
 * Usage: ts-node scripts/gen-registry.ts <manifest.json> <output-dir> [--interface-path <path>]
 *   --interface-path: import prefix for the registry contracts, default
 *                     "contracts/upgrades/registry".
 */

import * as fs from "fs";
import * as path from "path";

interface CoreContractEntry {
  proxy: string;
  implOld?: string;
  implNew?: string;
  implNewCodehash?: string;
}

interface FacetEntry {
  name: string;
  selectors: string[];
}

interface L2ForceDeployment {
  contract: string;
  upgradeType: "EraForceDeployment" | "ZKsyncOSSystemProxyUpgrade" | "ZKsyncOSUnsafeForceDeployment";
  deployedBytecodeInfo: string;
  newAddress: string;
  bytecodeHash: string;
}

interface CTMManifest {
  name: string;
  isZKsyncOS: boolean;
  ctmProxy: string;
  verifierOld: string;
  verifierNew: string;
  contracts: Record<string, { old?: string; new?: string; newCodehash?: string }>;
  facets: { old: FacetEntry[]; new: FacetEntry[] };
  facetFreezability: Record<string, boolean>;
  l2: {
    forceDeployments: L2ForceDeployment[];
    delegateTo: string;
    delegateCalldata: string;
    factoryDepHashes: string[];
    baseSystemContracts: { bootloader: string; defaultAccount: string; evmEmulator: string };
    fixedForceDeploymentsData: string;
    chainCreationInitCalldata: string;
  };
  genesis: {
    genesisUpgrade: string;
    batchHash: string;
    batchCommitment: string;
    indexRepeatedStorageChanges: number;
  };
}

interface Manifest {
  tag: string;
  oldVersion: string;
  newVersion: string;
  core: {
    proxyAdmin: string;
    ctmRegistries: { era: string; zksyncOS: string };
    contracts: Record<string, CoreContractEntry>;
  };
  ctms: CTMManifest[];
}

function packSemVer(version: string): bigint {
  const parts = version.split(".").map((p) => BigInt(p));
  if (parts.length !== 3) throw new Error(`invalid semver: ${version}`);
  const [major, minor, patch] = parts;
  // BigInt literals require ES2020; construct the shift amounts explicitly instead.
  return (major << BigInt(64)) | (minor << BigInt(32)) | patch;
}

function addr(a: string): string {
  // Addresses are emitted lowercase; Solidity accepts 40-hex-digit literals only when EIP-55
  // checksummed. To stay dependency-free, prepend `00` so the literal is a plain number and
  // cast it back down to an address.
  return `address(uint160(0x00${a.slice(2).toLowerCase()}))`;
}

function hexBytes(h: string): string {
  return `hex"${h.replace(/^0x/, "")}"`;
}

function banner(manifestPath: string): string {
  return `// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from ${path.basename(manifestPath)}.
// This file contains DATA ONLY; the lookup logic lives in the hand-written registry base.
// Every value is a compile-time constant: deploying the registry IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.`;
}

function selectorFill(varName: string, selectors: string[], indent: string): string[] {
  const out = [`${indent}${varName} = new bytes4[](${selectors.length});`];
  selectors.forEach((s, i) => out.push(`${indent}${varName}[${i}] = bytes4(${s.startsWith("0x") ? s : "0x" + s});`));
  return out;
}

/* ------------------------------------------------------------------ */
/*                              Core side                              */
/* ------------------------------------------------------------------ */

function generateCore(m: Manifest, manifestPath: string, ifacePath: string): { data: string; shim: string } {
  const name = `CoreRegistry${m.tag}`;
  const oldV = packSemVer(m.oldVersion);
  const newV = packSemVer(m.newVersion);
  const entries = Object.entries(m.core.contracts);

  const rows = entries
    .map(
      ([c, e]) => `        rows[i] = CoreRegistryBase.EcosystemContractRow({
            key: EcosystemContract.${c},
            proxy: ${addr(e.proxy)},
            implOld: ${e.implOld ? addr(e.implOld) : "address(0)"},
            implNew: ${e.implNew ? addr(e.implNew) : "address(0)"}
        }); // ${c}
        ++i;`
    )
    .join("\n");

  const pinned = entries.filter(([, e]) => e.implNew && e.implNewCodehash);
  const pinRows = pinned
    .map(
      ([c, e]) => `        pins[i] = CoreRegistryBase.CodehashPin({
            target: ${addr(e.implNew!)},
            expectedCodehash: ${e.implNewCodehash}
        }); // ${c} implNew
        ++i;`
    )
    .join("\n");

  const data = `// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

${banner(manifestPath)}

import {EcosystemContract} from "${ifacePath}/ContractIdentifiers.sol";
import {CoreRegistryBase} from "${ifacePath}/CoreRegistryBase.sol";

library ${name}Data {
    uint256 internal constant OLD_PROTOCOL_VERSION = ${oldV}; // ${m.oldVersion}
    uint256 internal constant NEW_PROTOCOL_VERSION = ${newV}; // ${m.newVersion}

    function proxyAdmin() internal pure returns (address) {
        return ${addr(m.core.proxyAdmin)};
    }

    function ctmRegistry(bool _isZKsyncOS) internal pure returns (address) {
        return _isZKsyncOS ? ${addr(m.core.ctmRegistries.zksyncOS)} : ${addr(m.core.ctmRegistries.era)};
    }

    function contractRows() internal pure returns (CoreRegistryBase.EcosystemContractRow[] memory rows) {
        rows = new CoreRegistryBase.EcosystemContractRow[](${entries.length});
        uint256 i = 0;
${rows}
    }

    function codehashPins() internal pure returns (CoreRegistryBase.CodehashPin[] memory pins) {
        pins = new CoreRegistryBase.CodehashPin[](${pinned.length});
        uint256 i = 0;
${pinRows}
    }
}
`;

  const shim = `// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

${banner(manifestPath)}

import {CoreRegistryBase} from "${ifacePath}/CoreRegistryBase.sol";
import {${name}Data} from "./${name}Data.sol";

contract ${name} is CoreRegistryBase {
    function _oldProtocolVersion() internal pure override returns (uint256) {
        return ${name}Data.OLD_PROTOCOL_VERSION;
    }

    function _newProtocolVersion() internal pure override returns (uint256) {
        return ${name}Data.NEW_PROTOCOL_VERSION;
    }

    function _proxyAdmin() internal pure override returns (address) {
        return ${name}Data.proxyAdmin();
    }

    function _ctmRegistry(bool _isZKsyncOS) internal pure override returns (address) {
        return ${name}Data.ctmRegistry(_isZKsyncOS);
    }

    function _contractRows() internal pure override returns (CoreRegistryBase.EcosystemContractRow[] memory) {
        return ${name}Data.contractRows();
    }

    function _codehashPins() internal pure override returns (CoreRegistryBase.CodehashPin[] memory) {
        return ${name}Data.codehashPins();
    }
}
`;
  return { data, shim };
}

/* ------------------------------------------------------------------ */
/*                               CTM side                              */
/* ------------------------------------------------------------------ */

function generateCTM(
  m: Manifest,
  ctm: CTMManifest,
  manifestPath: string,
  ifacePath: string
): { name: string; data: string; shim: string } {
  const name = `${ctm.name}CTMRegistry${m.tag}`;
  const oldV = packSemVer(m.oldVersion);
  const newV = packSemVer(m.newVersion);

  const addressRowsList: string[] = [];
  for (const [c, e] of Object.entries(ctm.contracts)) {
    if (e.old)
      addressRowsList.push(
        `        rows[i] = CTMRegistryBase.AddressRow({key: CTMContract.${c}, protocolVersion: OLD_PROTOCOL_VERSION, value: ${addr(
          e.old
        )}}); // ${c} @ ${m.oldVersion}\n        ++i;`
      );
    if (e.new)
      addressRowsList.push(
        `        rows[i] = CTMRegistryBase.AddressRow({key: CTMContract.${c}, protocolVersion: NEW_PROTOCOL_VERSION, value: ${addr(
          e.new
        )}}); // ${c} @ ${m.newVersion}\n        ++i;`
      );
  }

  const facetRowsList: string[] = [];
  const facetRow = (f: FacetEntry, versionConst: string, versionLabel: string): string => {
    const lines = [
      "        {",
      "            bytes4[] memory selectorList;",
      ...(f.selectors.length > 0 ? selectorFill("selectorList", f.selectors, "            ") : []),
      `            rows[i] = CTMRegistryBase.FacetRow({facet: CTMContract.${f.name}, protocolVersion: ${versionConst}, selectorList: selectorList}); // ${f.name} @ ${versionLabel}`,
      "            ++i;",
      "        }",
    ];
    return lines.join("\n");
  };
  for (const f of ctm.facets.old) facetRowsList.push(facetRow(f, "OLD_PROTOCOL_VERSION", m.oldVersion));
  for (const f of ctm.facets.new) facetRowsList.push(facetRow(f, "NEW_PROTOCOL_VERSION", m.newVersion));

  const freezabilityRowsList = Object.entries(ctm.facetFreezability).map(
    ([f, freezable]) =>
      `        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.${f}, isFreezable: ${freezable}}); // ${f}\n        ++i;`
  );

  const l2RowsList = ctm.l2.forceDeployments.map(
    (d) => `        rows[i] = CTMRegistryBase.L2DeploymentRow({
            key: CoreContract.${d.contract},
            info: IComplexUpgrader.UniversalContractUpgradeInfo({
                upgradeType: IComplexUpgrader.ContractUpgradeType.${d.upgradeType},
                deployedBytecodeInfo: ${hexBytes(d.deployedBytecodeInfo)},
                newAddress: ${addr(d.newAddress)}
            }),
            bytecodeHash: ${d.bytecodeHash}
        }); // ${d.contract}
        ++i;`
  );

  const factoryDeps = ctm.l2.factoryDepHashes.map((h, i) => `        hashes[${i}] = uint256(${h});`);

  const pinned = Object.entries(ctm.contracts).filter(([, e]) => e.new && e.newCodehash);
  const pinRows = pinned.map(
    ([c, e]) => `        pins[i] = CTMRegistryBase.CodehashPin({
            target: ${addr(e.new!)},
            expectedCodehash: ${e.newCodehash}
        }); // ${c} @ ${m.newVersion}
        ++i;`
  );

  const data = `// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

${banner(manifestPath)}

import {CoreContract, CTMContract} from "${ifacePath}/ContractIdentifiers.sol";
import {CTMRegistryBase} from "${ifacePath}/CTMRegistryBase.sol";
import {IComplexUpgrader} from "contracts/state-transition/l2-deps/IComplexUpgrader.sol";

library ${name}Data {
    uint256 internal constant OLD_PROTOCOL_VERSION = ${oldV}; // ${m.oldVersion}
    uint256 internal constant NEW_PROTOCOL_VERSION = ${newV}; // ${m.newVersion}

    function isZKsyncOS() internal pure returns (bool) {
        return ${ctm.isZKsyncOS};
    }

    function ctmProxy() internal pure returns (address) {
        return ${addr(ctm.ctmProxy)};
    }

    function ctmAddressRows() internal pure returns (CTMRegistryBase.AddressRow[] memory rows) {
        rows = new CTMRegistryBase.AddressRow[](${addressRowsList.length});
        uint256 i = 0;
${addressRowsList.join("\n")}
    }

    /// @dev \`AddressRow.key\` is unused for verifier rows (set to the first enum variant).
    function verifierRows() internal pure returns (CTMRegistryBase.AddressRow[] memory rows) {
        rows = new CTMRegistryBase.AddressRow[](2);
        rows[0] = CTMRegistryBase.AddressRow({key: CTMContract.AdminFacet, protocolVersion: OLD_PROTOCOL_VERSION, value: ${addr(
          ctm.verifierOld
        )}}); // verifier @ ${m.oldVersion}
        rows[1] = CTMRegistryBase.AddressRow({key: CTMContract.AdminFacet, protocolVersion: NEW_PROTOCOL_VERSION, value: ${addr(
          ctm.verifierNew
        )}}); // verifier @ ${m.newVersion}
    }

    function facetRows() internal pure returns (CTMRegistryBase.FacetRow[] memory rows) {
        rows = new CTMRegistryBase.FacetRow[](${facetRowsList.length});
        uint256 i = 0;
${facetRowsList.join("\n")}
    }

    function freezabilityRows() internal pure returns (CTMRegistryBase.FreezabilityRow[] memory rows) {
        rows = new CTMRegistryBase.FreezabilityRow[](${freezabilityRowsList.length});
        uint256 i = 0;
${freezabilityRowsList.join("\n")}
    }

    function l2DeploymentRows() internal pure returns (CTMRegistryBase.L2DeploymentRow[] memory rows) {
        rows = new CTMRegistryBase.L2DeploymentRow[](${l2RowsList.length});
        uint256 i = 0;
${l2RowsList.join("\n")}
    }

    function l2UpgradeDelegate() internal pure returns (address delegateTo, bytes memory delegateCalldata) {
        return (${addr(ctm.l2.delegateTo)}, ${hexBytes(ctm.l2.delegateCalldata)});
    }

    function factoryDepHashes() internal pure returns (uint256[] memory hashes) {
        hashes = new uint256[](${ctm.l2.factoryDepHashes.length});
${factoryDeps.join("\n")}
    }

    function baseSystemContractHashes()
        internal
        pure
        returns (bytes32 bootloaderHash, bytes32 defaultAccountHash, bytes32 evmEmulatorHash)
    {
        return (
            ${ctm.l2.baseSystemContracts.bootloader},
            ${ctm.l2.baseSystemContracts.defaultAccount},
            ${ctm.l2.baseSystemContracts.evmEmulator}
        );
    }

    function fixedForceDeploymentsData() internal pure returns (bytes memory) {
        return ${hexBytes(ctm.l2.fixedForceDeploymentsData)};
    }

    function chainCreationInitCalldata() internal pure returns (bytes memory) {
        return ${hexBytes(ctm.l2.chainCreationInitCalldata)};
    }

    function genesisParams()
        internal
        pure
        returns (
            address genesisUpgrade,
            bytes32 genesisBatchHash,
            bytes32 genesisBatchCommitment,
            uint64 genesisIndexRepeatedStorageChanges
        )
    {
        return (
            ${addr(ctm.genesis.genesisUpgrade)},
            ${ctm.genesis.batchHash},
            ${ctm.genesis.batchCommitment},
            ${ctm.genesis.indexRepeatedStorageChanges}
        );
    }

    function codehashPins() internal pure returns (CTMRegistryBase.CodehashPin[] memory pins) {
        pins = new CTMRegistryBase.CodehashPin[](${pinRows.length});
        uint256 i = 0;
${pinRows.join("\n")}
    }
}
`;

  const shim = `// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

${banner(manifestPath)}

import {CTMRegistryBase} from "${ifacePath}/CTMRegistryBase.sol";
import {${name}Data} from "./${name}Data.sol";

contract ${name} is CTMRegistryBase {
    function _isZKsyncOS() internal pure override returns (bool) {
        return ${name}Data.isZKsyncOS();
    }

    function _oldProtocolVersion() internal pure override returns (uint256) {
        return ${name}Data.OLD_PROTOCOL_VERSION;
    }

    function _newProtocolVersion() internal pure override returns (uint256) {
        return ${name}Data.NEW_PROTOCOL_VERSION;
    }

    function _ctmProxy() internal pure override returns (address) {
        return ${name}Data.ctmProxy();
    }

    function _ctmAddressRows() internal pure override returns (CTMRegistryBase.AddressRow[] memory) {
        return ${name}Data.ctmAddressRows();
    }

    function _verifierRows() internal pure override returns (CTMRegistryBase.AddressRow[] memory) {
        return ${name}Data.verifierRows();
    }

    function _facetRows() internal pure override returns (CTMRegistryBase.FacetRow[] memory) {
        return ${name}Data.facetRows();
    }

    function _freezabilityRows() internal pure override returns (CTMRegistryBase.FreezabilityRow[] memory) {
        return ${name}Data.freezabilityRows();
    }

    function _l2DeploymentRows() internal pure override returns (CTMRegistryBase.L2DeploymentRow[] memory) {
        return ${name}Data.l2DeploymentRows();
    }

    function _l2UpgradeDelegate() internal pure override returns (address, bytes memory) {
        return ${name}Data.l2UpgradeDelegate();
    }

    function _factoryDepHashes() internal pure override returns (uint256[] memory) {
        return ${name}Data.factoryDepHashes();
    }

    function _baseSystemContractHashes() internal pure override returns (bytes32, bytes32, bytes32) {
        return ${name}Data.baseSystemContractHashes();
    }

    function _fixedForceDeploymentsData() internal pure override returns (bytes memory) {
        return ${name}Data.fixedForceDeploymentsData();
    }

    function _chainCreationInitCalldata() internal pure override returns (bytes memory) {
        return ${name}Data.chainCreationInitCalldata();
    }

    function _genesisParams() internal pure override returns (address, bytes32, bytes32, uint64) {
        return ${name}Data.genesisParams();
    }

    function _codehashPins() internal pure override returns (CTMRegistryBase.CodehashPin[] memory) {
        return ${name}Data.codehashPins();
    }
}
`;
  return { name, data, shim };
}

/* ------------------------------------------------------------------ */

function main() {
  const [manifestPath, outDir] = process.argv.slice(2);
  if (!manifestPath || !outDir) {
    console.error("Usage: ts-node scripts/gen-registry.ts <manifest.json> <output-dir> [--interface-path <p>]");
    process.exit(1);
  }
  const ifaceFlag = process.argv.indexOf("--interface-path");
  const ifacePath = ifaceFlag > 0 ? process.argv[ifaceFlag + 1] : "contracts/upgrades/registry";

  const manifest: Manifest = JSON.parse(fs.readFileSync(manifestPath, "utf-8"));
  fs.mkdirSync(outDir, { recursive: true });

  const core = generateCore(manifest, manifestPath, ifacePath);
  const coreName = `CoreRegistry${manifest.tag}`;
  fs.writeFileSync(path.join(outDir, `${coreName}Data.sol`), core.data);
  fs.writeFileSync(path.join(outDir, `${coreName}.sol`), core.shim);
  console.log(`generated ${path.join(outDir, coreName)}{,Data}.sol`);

  for (const ctm of manifest.ctms) {
    const g = generateCTM(manifest, ctm, manifestPath, ifacePath);
    fs.writeFileSync(path.join(outDir, `${g.name}Data.sol`), g.data);
    fs.writeFileSync(path.join(outDir, `${g.name}.sol`), g.shim);
    console.log(`generated ${path.join(outDir, g.name)}{,Data}.sol`);
  }
}

main();
