// SPDX-License-Identifier: MIT
//
// Patch (hashes-only) for the ZKsync OS chain type manager (CTM) upgrade data,
// motivated by https://github.com/matter-labs/era-contracts/pull/2224.
//
// PR #2224 changed the bytecode of `L2AssetTracker` (and, transitively, a few
// other contracts). The already-prepared v31 upgrade artifacts therefore embed
// stale ZKsync-OS bytecode descriptors for the ZKsync OS CTM. This script
// regenerates the affected CTM data (`force_deployments_data` and
// `chain_upgrade_diamond_cut`) for the ZKsync OS CTM ONLY.
//
// Unlike the forge counterpart (`PatchZkosCtmAssetTracker.s.sol`), this script
// NEVER touches the actual bytecode. It:
//   1. decodes the existing chain-creation params / upgrade data,
//   2. locates every place that embeds a bytecode descriptor that "involved the
//      old upgrade" (the asset-tracker force deployment and the v31 upgrade
//      delegate),
//   3. rewrites those descriptors to the NEW hashes taken purely from
//      `AllContractsHashes.json`,
//   4. double-checks that every stale reference has been replaced and that the
//      patched data only references bytecodes whose hashes are present in
//      `AllContractsHashes.json`.
//
// The produced blobs are byte-for-byte identical to the ones generated by the
// forge script (which derives the hashes from the real compiled bytecode), so
// running both and diffing the outputs validates that `AllContractsHashes.json`
// is consistent with the actual artifacts.

import { ethers } from "ethers";
import * as fs from "fs";
import * as path from "path";
import * as toml from "toml";

const abi = ethers.utils.defaultAbiCoder;

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

// The descriptors that "involved the old upgrade" for the ZKsync OS CTM:
//  - the L2 asset tracker, force-deployed via the fixed force-deployments data
//    (`FixedForceDeploymentsData.assetTrackerBytecodeInfo`), and
//  - the `L2V31Upgrade` delegate, force-deployed via the single
//    `ZKsyncOSUnsafeForceDeployment` entry in the upgrade transaction.
const ASSET_TRACKER_CONTRACT = "l1-contracts/L2AssetTracker";
const V31_UPGRADE_CONTRACT = "l1-contracts/L2V31Upgrade";

// `ContractUpgradeType` enum (contracts/state-transition/l2-deps/IComplexUpgrader.sol)
const UPGRADE_TYPE_ZKSYNCOS_UNSAFE_FORCE_DEPLOYMENT = 2;

const REPO_ROOT = path.resolve(__dirname, "..", "..");
const DEFAULT_HASHES = path.join(REPO_ROOT, "AllContractsHashes.json");
const DEFAULT_ECOSYSTEM = path.join(
  REPO_ROOT,
  "l1-contracts/upgrade-envs/v0.31.0-interopB/output/stage/ecosystem.toml"
);
const DEFAULT_OUTPUT = path.join(REPO_ROOT, "l1-contracts/script-out/zkos-ctm-asset-tracker-patch.ts.json");

// ---------------------------------------------------------------------------
// ABI type descriptors (encoding-only, no contract ABIs are declared)
// ---------------------------------------------------------------------------

const DIAMOND_CUT_DATA =
  "tuple(tuple(address facet,uint8 action,bool isFreezable,bytes4[] selectors)[] facetCuts,address initAddress,bytes initCalldata)";

const L2_CANONICAL_TX =
  "tuple(uint256 txType,uint256 from,uint256 to,uint256 gasLimit,uint256 gasPerPubdataByteLimit,uint256 maxFeePerGas," +
  "uint256 maxPriorityFeePerGas,uint256 paymaster,uint256 nonce,uint256 value,uint256[4] reserved,bytes data,bytes signature," +
  "uint256[] factoryDeps,bytes paymasterInput,bytes reservedDynamic)";

const PROPOSED_UPGRADE =
  `tuple(${L2_CANONICAL_TX} l2ProtocolUpgradeTx,bytes32 bootloaderHash,bytes32 defaultAccountHash,bytes32 evmEmulatorHash,` +
  "address verifier,tuple(bytes32 recursionNodeLevelVkHash,bytes32 recursionLeafLevelVkHash,bytes32 recursionCircuitsSetVksHash) verifierParams," +
  "bytes l1ContractsUpgradeCalldata,bytes postUpgradeCalldata,uint256 upgradeTimestamp,uint256 newProtocolVersion)";

const FIXED_FORCE_DEPLOYMENTS_DATA =
  "tuple(uint256 l1ChainId,uint256 gatewayChainId,uint256 eraChainId,address l1AssetRouter,bytes32 l2TokenProxyBytecodeHash," +
  "address aliasedL1Governance,uint256 maxNumberOfZKChains,bytes bridgehubBytecodeInfo,bytes l2AssetRouterBytecodeInfo," +
  "bytes l2NtvBytecodeInfo,bytes messageRootBytecodeInfo,bytes chainAssetHandlerBytecodeInfo,bytes interopCenterBytecodeInfo," +
  "bytes interopHandlerBytecodeInfo,bytes assetTrackerBytecodeInfo,bytes beaconDeployerInfo,bytes baseTokenHolderBytecodeInfo," +
  "address l2SharedBridgeLegacyImpl,address l2BridgedStandardERC20Impl,address aliasedChainRegistrationSender," +
  "address dangerousTestOnlyForcedBeacon,bytes32 zkTokenAssetId)";

const UNIVERSAL_CONTRACT_UPGRADE_INFO = "tuple(uint8 upgradeType,bytes deployedBytecodeInfo,address newAddress)";

// ---------------------------------------------------------------------------
// Bytecode descriptors
// ---------------------------------------------------------------------------

// A ZKsync OS bytecode descriptor: abi.encode(bytes32 blake2s, uint32 length, bytes32 keccak).
// See contracts/common/libraries/ZKSyncOSBytecodeInfo.sol.
interface ZkosBytecodeInfo {
  blake: string; // 0x-prefixed bytes32
  length: number;
  keccak: string; // 0x-prefixed bytes32
}

function decodeZkosBytecodeInfo(infoHex: string): ZkosBytecodeInfo {
  const [blake, length, keccak] = abi.decode(["bytes32", "uint32", "bytes32"], infoHex);
  return { blake, length: Number(length), keccak };
}

function encodeZkosBytecodeInfo(info: ZkosBytecodeInfo): string {
  return abi.encode(["bytes32", "uint32", "bytes32"], [info.blake, info.length, info.keccak]);
}

// `generateRandomAddress` from contracts/l2-upgrades/L2GenesisForceDeploymentsHelper.sol:
// address(uint160(uint256(keccak256(bytes.concat(bytes32(0), bytecodeInfo))))).
function generateRandomAddress(bytecodeInfoHex: string): string {
  const packed = ethers.utils.hexConcat([ethers.constants.HashZero, bytecodeInfoHex]);
  const hash = ethers.utils.keccak256(packed);
  return ethers.utils.getAddress("0x" + hash.slice(-40));
}

function infoFromHashesJson(entry: HashEntry): ZkosBytecodeInfo {
  if (
    !entry.evmDeployedBytecodeBlakeHash ||
    !entry.evmDeployedBytecodeHash ||
    entry.evmDeployedBytecodeLength == null
  ) {
    throw new Error(`Missing EVM deployed bytecode hashes for ${entry.contractName}`);
  }
  return {
    blake: entry.evmDeployedBytecodeBlakeHash,
    length: entry.evmDeployedBytecodeLength,
    keccak: entry.evmDeployedBytecodeHash,
  };
}

// ---------------------------------------------------------------------------
// AllContractsHashes.json
// ---------------------------------------------------------------------------

interface HashEntry {
  contractName: string;
  evmDeployedBytecodeHash: string | null;
  evmDeployedBytecodeBlakeHash: string | null;
  evmDeployedBytecodeLength: number | null;
}

function loadHashes(filePath: string): Map<string, HashEntry> {
  const arr: HashEntry[] = JSON.parse(fs.readFileSync(filePath, "utf8"));
  const map = new Map<string, HashEntry>();
  for (const e of arr) {
    map.set(e.contractName, e);
  }
  return map;
}

// Every keccak hash referenced by the patched data must resolve to one of these.
function allKnownKeccaks(hashes: Map<string, HashEntry>): Set<string> {
  const set = new Set<string>();
  for (const e of hashes.values()) {
    if (e.evmDeployedBytecodeHash && e.evmDeployedBytecodeHash !== "0x") {
      set.add(e.evmDeployedBytecodeHash.toLowerCase());
    }
  }
  return set;
}

// ---------------------------------------------------------------------------
// Hex helpers (byte-accurate, layout-preserving substitution)
// ---------------------------------------------------------------------------

function strip0x(s: string): string {
  return s.toLowerCase().replace(/^0x/, "");
}

function countOccurrences(haystack: string, needle: string): number {
  let count = 0;
  let idx = haystack.indexOf(needle);
  while (idx !== -1) {
    count++;
    idx = haystack.indexOf(needle, idx + needle.length);
  }
  return count;
}

interface Substitution {
  label: string;
  oldHex: string; // without 0x
  newHex: string; // without 0x
  expected: number; // expected number of occurrences
}

// Applies the substitutions to a 0x-prefixed blob, asserting occurrence counts.
function applySubstitutions(blobHex: string, subs: Substitution[]): string {
  let body = strip0x(blobHex);
  for (const sub of subs) {
    if (sub.oldHex.length !== sub.newHex.length) {
      throw new Error(`${sub.label}: substitution length mismatch (layout would break)`);
    }
    const found = countOccurrences(body, sub.oldHex);
    if (found !== sub.expected) {
      throw new Error(`${sub.label}: expected ${sub.expected} occurrence(s) of old value, found ${found}`);
    }
    body = body.split(sub.oldHex).join(sub.newHex);
  }
  return "0x" + body;
}

// ---------------------------------------------------------------------------
// Structural decoding of the ZKsync OS CTM data
// ---------------------------------------------------------------------------

// The asset-tracker descriptor lives in `FixedForceDeploymentsData.assetTrackerBytecodeInfo`
// as abi.encode(implInfo, proxyInfo); we only care about the implementation part.
function readAssetTrackerInfoFromFfd(ffdHex: string): ZkosBytecodeInfo {
  const [ffd] = abi.decode([FIXED_FORCE_DEPLOYMENTS_DATA], ffdHex);
  const [implInfo] = abi.decode(["bytes", "bytes"], ffd.assetTrackerBytecodeInfo);
  return decodeZkosBytecodeInfo(implInfo);
}

interface UpgradeCutParts {
  deployments: Array<{ upgradeType: number; deployedBytecodeInfo: string; newAddress: string }>;
  delegateTo: string;
  innerForceDeploymentsData: string;
  factoryDeps: string[]; // 0x-prefixed bytes32 keccak hashes
}

function decodeUpgradeCut(chainUpgradeDiamondCutHex: string): UpgradeCutParts {
  const [dcd] = abi.decode([DIAMOND_CUT_DATA], chainUpgradeDiamondCutHex);
  // initCalldata = DefaultUpgrade.upgrade(ProposedUpgrade) -> strip 4-byte selector.
  const [proposedUpgrade] = abi.decode([PROPOSED_UPGRADE], "0x" + strip0x(dcd.initCalldata).slice(8));
  const tx = proposedUpgrade.l2ProtocolUpgradeTx;
  const factoryDeps: string[] = tx.factoryDeps.map((d: ethers.BigNumber) =>
    ethers.utils.hexZeroPad(d.toHexString(), 32)
  );
  // tx.data = forceDeployAndUpgradeUniversal(deployments, delegateTo, innerCalldata).
  const txDataBody = "0x" + strip0x(tx.data).slice(8);
  const [deploymentsRaw, delegateTo, inner] = abi.decode(
    [`${UNIVERSAL_CONTRACT_UPGRADE_INFO}[]`, "address", "bytes"],
    txDataBody
  );
  const deployments = deploymentsRaw.map(
    (d: { upgradeType: number; deployedBytecodeInfo: string; newAddress: string }) => ({
      upgradeType: Number(d.upgradeType),
      deployedBytecodeInfo: d.deployedBytecodeInfo,
      newAddress: d.newAddress,
    })
  );
  // inner = IL2V31Upgrade.upgrade(bool, address, bytes forceDeploymentsData, bytes) -> strip selector.
  const [, , innerForceDeploymentsData] = abi.decode(
    ["bool", "address", "bytes", "bytes"],
    "0x" + strip0x(inner).slice(8)
  );
  return { deployments, delegateTo, innerForceDeploymentsData, factoryDeps };
}

function findV31DelegateInfo(parts: UpgradeCutParts): ZkosBytecodeInfo {
  const unsafe = parts.deployments.filter((d) => d.upgradeType === UPGRADE_TYPE_ZKSYNCOS_UNSAFE_FORCE_DEPLOYMENT);
  if (unsafe.length !== 1) {
    throw new Error(`Expected exactly one ZKsyncOSUnsafeForceDeployment (v31 delegate), found ${unsafe.length}`);
  }
  return decodeZkosBytecodeInfo(unsafe[0].deployedBytecodeInfo);
}

// Collect every keccak hash referenced by a force-deployments blob (each
// `*BytecodeInfo` may be a single descriptor or an abi.encode(impl, proxy) pair).
function collectFfdKeccaks(ffdHex: string): string[] {
  const [ffd] = abi.decode([FIXED_FORCE_DEPLOYMENTS_DATA], ffdHex);
  const infoFields = [
    ffd.bridgehubBytecodeInfo,
    ffd.l2AssetRouterBytecodeInfo,
    ffd.l2NtvBytecodeInfo,
    ffd.messageRootBytecodeInfo,
    ffd.chainAssetHandlerBytecodeInfo,
    ffd.interopCenterBytecodeInfo,
    ffd.interopHandlerBytecodeInfo,
    ffd.assetTrackerBytecodeInfo,
    ffd.beaconDeployerInfo,
    ffd.baseTokenHolderBytecodeInfo,
  ];
  const keccaks: string[] = [];
  for (const field of infoFields) {
    if (!field || strip0x(field).length === 0) continue;
    const [implInfo, proxyInfo] = abi.decode(["bytes", "bytes"], field);
    keccaks.push(decodeZkosBytecodeInfo(implInfo).keccak.toLowerCase());
    keccaks.push(decodeZkosBytecodeInfo(proxyInfo).keccak.toLowerCase());
  }
  return keccaks;
}

// Collect every keccak hash referenced by the upgrade-cut blob.
function collectUpgradeCutKeccaks(chainUpgradeDiamondCutHex: string): string[] {
  const parts = decodeUpgradeCut(chainUpgradeDiamondCutHex);
  const keccaks: string[] = [];
  for (const dep of parts.deployments) {
    if (dep.upgradeType === UPGRADE_TYPE_ZKSYNCOS_UNSAFE_FORCE_DEPLOYMENT) {
      keccaks.push(decodeZkosBytecodeInfo(dep.deployedBytecodeInfo).keccak.toLowerCase());
    } else {
      const [implInfo, proxyInfo] = abi.decode(["bytes", "bytes"], dep.deployedBytecodeInfo);
      keccaks.push(decodeZkosBytecodeInfo(implInfo).keccak.toLowerCase());
      keccaks.push(decodeZkosBytecodeInfo(proxyInfo).keccak.toLowerCase());
    }
  }
  for (const fd of parts.factoryDeps) {
    keccaks.push(fd.toLowerCase());
  }
  keccaks.push(...collectFfdKeccaks(parts.innerForceDeploymentsData));
  return keccaks;
}

// Assert that every keccak referenced by the patched data resolves to a hash in
// AllContractsHashes.json. This is the strong "no stale reference left behind"
// completeness check: any contract whose bytecode changed but was missed would
// leave a keccak that is absent from the current hashes file.
function assertNoStaleReferences(label: string, keccaks: string[], known: Set<string>): void {
  const stale = keccaks.filter((k) => !known.has(k));
  if (stale.length > 0) {
    throw new Error(
      `${label}: ${stale.length} stale bytecode reference(s) not present in AllContractsHashes.json: ${[
        ...new Set(stale),
      ].join(", ")}`
    );
  }
}

// ---------------------------------------------------------------------------
// TOML helpers
// ---------------------------------------------------------------------------

function readEcosystem(filePath: string): {
  forceDeploymentsData: string;
  chainUpgradeDiamondCut: string;
  diamondCutData: string;
} {
  const parsed = toml.parse(fs.readFileSync(filePath, "utf8"));
  const zk = parsed?.ctms?.zksync_os;
  if (!zk) {
    throw new Error("ecosystem.toml has no [ctms.zksync_os] section");
  }
  return {
    forceDeploymentsData: zk.contracts_config.force_deployments_data,
    chainUpgradeDiamondCut: zk.chain_upgrade_diamond_cut,
    diamondCutData: zk.contracts_config.diamond_cut_data,
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const hashesPath = process.env.HASHES_JSON || DEFAULT_HASHES;
  const ecosystemPath = process.env.ECOSYSTEM_TOML || DEFAULT_ECOSYSTEM;
  const outputPath = process.env.PATCH_OUTPUT || DEFAULT_OUTPUT;

  console.log("Patching ZKsync OS CTM asset-tracker upgrade data (hashes-only, TS)");
  console.log(`  hashes:     ${hashesPath}`);
  console.log(`  ecosystem:  ${ecosystemPath}`);
  console.log(`  output:     ${outputPath}`);

  const hashes = loadHashes(hashesPath);
  const known = allKnownKeccaks(hashes);
  const eco = readEcosystem(ecosystemPath);

  // --- locate the OLD descriptors that involved the old upgrade -------------
  const assetTrackerOld = readAssetTrackerInfoFromFfd(eco.forceDeploymentsData);
  const upgradeParts = decodeUpgradeCut(eco.chainUpgradeDiamondCut);
  const v31Old = findV31DelegateInfo(upgradeParts);

  // Sanity: the descriptor embedded in the upgrade-cut's force deployments data
  // must match the one in the standalone force deployments data.
  const assetTrackerOldInUpgrade = readAssetTrackerInfoFromFfd(upgradeParts.innerForceDeploymentsData);
  if (encodeZkosBytecodeInfo(assetTrackerOld) !== encodeZkosBytecodeInfo(assetTrackerOldInUpgrade)) {
    throw new Error("Asset tracker descriptor differs between force-deployments data and upgrade cut");
  }

  // --- the NEW descriptors come ONLY from AllContractsHashes.json -----------
  const assetTrackerNew = infoFromHashesJson(hashes.get(ASSET_TRACKER_CONTRACT)!);
  const v31New = infoFromHashesJson(hashes.get(V31_UPGRADE_CONTRACT)!);

  // The old blobs were generated *before* the bytecode change, so the embedded
  // descriptors must differ from the current hashes. If they already match,
  // either the input is already patched or the contract did not actually change.
  const changes: Array<{ contract: string; old: ZkosBytecodeInfo; nw: ZkosBytecodeInfo }> = [];
  for (const [contract, oldInfo, newInfo] of [
    [ASSET_TRACKER_CONTRACT, assetTrackerOld, assetTrackerNew],
    [V31_UPGRADE_CONTRACT, v31Old, v31New],
  ] as Array<[string, ZkosBytecodeInfo, ZkosBytecodeInfo]>) {
    if (encodeZkosBytecodeInfo(oldInfo) === encodeZkosBytecodeInfo(newInfo)) {
      throw new Error(`${contract}: embedded descriptor already equals the hashes-json descriptor (nothing to patch)`);
    }
    changes.push({ contract, old: oldInfo, nw: newInfo });
    console.log(`  change ${contract}:`);
    console.log(`    old keccak ${oldInfo.keccak} len ${oldInfo.length}`);
    console.log(`    new keccak ${newInfo.keccak} len ${newInfo.length}`);
  }

  // The v31 delegate address is derived from its bytecode descriptor, so it must
  // be recomputed for the new descriptor.
  const delegateOld = generateRandomAddress(encodeZkosBytecodeInfo(v31Old));
  const delegateNew = generateRandomAddress(encodeZkosBytecodeInfo(v31New));
  if (ethers.utils.getAddress(delegateOld) !== ethers.utils.getAddress(upgradeParts.delegateTo)) {
    throw new Error("Recomputed old v31 delegate address does not match the decoded delegateTo");
  }
  console.log(`  v31 delegate ${delegateOld} -> ${delegateNew}`);

  // --- patch force_deployments_data -----------------------------------------
  const forceDeploymentsDataNew = applySubstitutions(eco.forceDeploymentsData, [
    {
      label: "force_deployments_data: assetTracker triple",
      oldHex: strip0x(encodeZkosBytecodeInfo(assetTrackerOld)),
      newHex: strip0x(encodeZkosBytecodeInfo(assetTrackerNew)),
      expected: 1,
    },
  ]);

  // --- patch chain_upgrade_diamond_cut --------------------------------------
  // Order matters: replace the 96-byte descriptors first (so the keccak inside
  // them is rewritten as part of the descriptor), then the standalone keccak
  // hashes in `factoryDeps`, then the derived delegate address (2 spots: the
  // `delegateTo` argument and the matching `newAddress`).
  const chainUpgradeDiamondCutNew = applySubstitutions(eco.chainUpgradeDiamondCut, [
    {
      label: "chain_upgrade: assetTracker triple",
      oldHex: strip0x(encodeZkosBytecodeInfo(assetTrackerOld)),
      newHex: strip0x(encodeZkosBytecodeInfo(assetTrackerNew)),
      expected: 2, // asset-tracker system-proxy deployment + embedded force-deployments data
    },
    {
      label: "chain_upgrade: v31 delegate triple",
      oldHex: strip0x(encodeZkosBytecodeInfo(v31Old)),
      newHex: strip0x(encodeZkosBytecodeInfo(v31New)),
      expected: 1,
    },
    {
      label: "chain_upgrade: assetTracker keccak (factoryDeps)",
      oldHex: strip0x(assetTrackerOld.keccak),
      newHex: strip0x(assetTrackerNew.keccak),
      expected: 1,
    },
    {
      label: "chain_upgrade: v31 keccak (factoryDeps)",
      oldHex: strip0x(v31Old.keccak),
      newHex: strip0x(v31New.keccak),
      expected: 1,
    },
    {
      label: "chain_upgrade: v31 delegate address",
      oldHex: strip0x(delegateOld),
      newHex: strip0x(delegateNew),
      expected: 2,
    },
  ]);

  // --- double-check the result ----------------------------------------------
  // 1. No old descriptor / keccak / delegate address may survive anywhere.
  for (const [label, blob] of [
    ["force_deployments_data", forceDeploymentsDataNew],
    ["chain_upgrade_diamond_cut", chainUpgradeDiamondCutNew],
  ] as Array<[string, string]>) {
    const body = strip0x(blob);
    for (const stale of [
      strip0x(assetTrackerOld.keccak),
      strip0x(assetTrackerOld.blake),
      strip0x(v31Old.keccak),
      strip0x(v31Old.blake),
      strip0x(delegateOld),
    ]) {
      if (body.includes(stale)) {
        throw new Error(`${label}: stale reference ${stale} still present after patching`);
      }
    }
  }

  // 2. Every bytecode reference in the patched data resolves to a current hash.
  assertNoStaleReferences("force_deployments_data", collectFfdKeccaks(forceDeploymentsDataNew), known);
  assertNoStaleReferences("chain_upgrade_diamond_cut", collectUpgradeCutKeccaks(chainUpgradeDiamondCutNew), known);

  // 3. The chain-creation diamond cut does not embed any of these descriptors,
  //    so it must be left untouched.
  const diamondCutBody = strip0x(eco.diamondCutData);
  for (const present of [strip0x(assetTrackerNew.keccak), strip0x(v31New.keccak)]) {
    if (diamondCutBody.includes(present)) {
      throw new Error("diamond_cut_data unexpectedly references an asset-tracker / v31 descriptor");
    }
  }

  const out = {
    source: {
      hashes: path.relative(REPO_ROOT, hashesPath),
      ecosystem: path.relative(REPO_ROOT, ecosystemPath),
    },
    ctm: "zksync_os",
    changedContracts: changes.map((c) => ({
      contract: c.contract,
      oldKeccak: c.old.keccak,
      newKeccak: c.nw.keccak,
      oldLength: c.old.length,
      newLength: c.nw.length,
    })),
    v31DelegateOld: ethers.utils.getAddress(delegateOld),
    v31DelegateNew: ethers.utils.getAddress(delegateNew),
    diamondCutDataUnchanged: eco.diamondCutData,
    forceDeploymentsData: forceDeploymentsDataNew,
    chainUpgradeDiamondCut: chainUpgradeDiamondCutNew,
  };

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, JSON.stringify(out, null, 2) + "\n");
  console.log(`\nAll checks passed. Patched ZKsync OS CTM data written to:\n  ${outputPath}`);

  // Optionally write a fully patched ecosystem.toml (the amended upgrade).
  // The old ZKsync OS `force_deployments_data` is a substring of the old
  // `chain_upgrade_diamond_cut`, so we replace the (longer) upgrade-cut value
  // first; afterwards the only remaining occurrence of the old force-deployments
  // value is its own standalone key.
  if (process.env.APPLY === "true") {
    const appliedPath = process.env.APPLY_OUTPUT || ecosystemPath.replace(/\.toml$/, ".patched.toml");
    const tomlText = fs.readFileSync(ecosystemPath, "utf8");

    // Restrict the replacement to the `[ctms.zksync_os]` section: the gateway
    // state transition (`[new_gateway...]`) shares the same force-deployments
    // blob, but it is a different CTM and is out of scope for this patch.
    const sectionStart = tomlText.indexOf("[ctms.zksync_os]");
    if (sectionStart === -1) {
      throw new Error("apply: [ctms.zksync_os] section not found");
    }
    // The section ends at the first top-level table that is not nested under it.
    const after = tomlText.slice(sectionStart + 1);
    const nextHeaderRel = after.search(/\n\[(?!ctms\.zksync_os)/);
    const sectionEnd = nextHeaderRel === -1 ? tomlText.length : sectionStart + 1 + nextHeaderRel;

    let section = tomlText.slice(sectionStart, sectionEnd);
    const replaceOnce = (label: string, oldVal: string, newVal: string) => {
      const occurrences = countOccurrences(section, oldVal);
      if (occurrences !== 1) {
        throw new Error(`apply: expected exactly one occurrence of ${label} in [ctms.zksync_os], found ${occurrences}`);
      }
      section = section.replace(oldVal, newVal);
    };
    // The standalone force-deployments value is a substring of the upgrade-cut
    // value, so replace the (longer) upgrade cut first.
    replaceOnce("chain_upgrade_diamond_cut", eco.chainUpgradeDiamondCut, chainUpgradeDiamondCutNew);
    replaceOnce("force_deployments_data", eco.forceDeploymentsData, forceDeploymentsDataNew);

    const patchedText = tomlText.slice(0, sectionStart) + section + tomlText.slice(sectionEnd);
    fs.writeFileSync(appliedPath, patchedText);
    console.log(`Amended upgrade (zksync_os CTM only) written to:\n  ${appliedPath}`);
  }
}

main();
