#!/usr/bin/env ts-node
/**
 * Script to populate LegacySharedBridgeAddresses.sol with data fetched from on-chain.
 *
 * Commands:
 *
 *   fetch --rpc <url> --env <name>
 *     Connects to the given L1 RPC, reads the bridgehub address from the permanent-values
 *     TOML file for <env>, queries all registered ZK chains, and for each chain checks
 *     whether it has a legacy L2SharedBridge (via L1Nullifier.__DEPRECATED_l2BridgeAddress).
 *     Results are saved to upgrade-envs/legacy-bridge-addresses/<env>.toml.
 *
 *   generate
 *     Reads stage.toml, testnet.toml, and mainnet.toml from the data directory and
 *     regenerates contracts/bridge/asset-tracker/LegacySharedBridgeAddresses.sol.
 */

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import * as hardhat from "hardhat";
import * as fs from "fs";
import * as path from "path";
import * as toml from "toml";
import { ethers } from "ethers";
import { Command } from "commander";

// ─── Paths ───────────────────────────────────────────────────────────────────

/** Directory containing per-environment permanent-values TOML files. */
const PERMANENT_VALUES_DIR = path.join(__dirname, "../upgrade-envs/permanent-values");

/**
 * Directory where fetched bridge data TOML files are stored (one per env).
 * These files are committed to the repository and read by the `generate` command.
 */
const BRIDGE_DATA_DIR = path.join(__dirname, "../upgrade-envs/permanent-values/legacy-bridge-addresses");

/** Path to the Solidity file that is regenerated by the `generate` command. */
const SOLIDITY_OUTPUT_FILE = path.join(__dirname, "../contracts/bridge/asset-tracker/LegacySharedBridgeAddresses.sol");

// ─── ABIs (read from Foundry output) ─────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-var-requires
const BRIDGEHUB_ABI = require("../out/IBridgehubBase.sol/IBridgehubBase.json").abi;
// eslint-disable-next-line @typescript-eslint/no-var-requires
const L1_ASSET_ROUTER_ABI = require("../out/IL1AssetRouter.sol/IL1AssetRouter.json").abi;
// eslint-disable-next-line @typescript-eslint/no-var-requires
const L1_NULLIFIER_ABI = require("../out/L1Nullifier.sol/L1Nullifier.json").abi;

// ─── Data types ───────────────────────────────────────────────────────────────

interface ChainBridgeEntry {
  /** The ZK chain ID. */
  chainId: number;
  /** Checksummed address of the legacy L2SharedBridge on this chain. */
  legacySharedBridgeAddress: string;
}

interface EnvBridgeData {
  /** Address of the L1AssetRouter for this ecosystem (from bridgehub.assetRouter()). */
  l1AssetRouterAddress: string;
  /** Chains that have a non-zero legacy L2SharedBridge address. */
  chains: ChainBridgeEntry[];
}

// ─── fetch command ────────────────────────────────────────────────────────────

async function fetchBridgeAddresses(rpc: string, envName: string): Promise<void> {
  const permanentValuesFile = path.join(PERMANENT_VALUES_DIR, `${envName}.toml`);

  if (!fs.existsSync(permanentValuesFile)) {
    throw new Error(`Permanent values file not found: ${permanentValuesFile}`);
  }

  const permanentValues = toml.parse(fs.readFileSync(permanentValuesFile, "utf-8"));
  const bridgehubAddress: string | undefined = permanentValues.core_contracts?.bridgehub_proxy_addr;

  if (!bridgehubAddress) {
    throw new Error(`core_contracts.bridgehub_proxy_addr not found in ${permanentValuesFile}`);
  }

  console.log(`Bridgehub:      ${bridgehubAddress}`);

  const provider = new ethers.providers.JsonRpcProvider(rpc);
  const bridgehub = new ethers.Contract(bridgehubAddress, BRIDGEHUB_ABI, provider);

  // 1. Fetch all registered ZK chain IDs from the Bridgehub.
  const rawChainIds: ethers.BigNumber[] = await bridgehub.getAllZKChainChainIDs();
  console.log(`Chains found:   ${rawChainIds.length}`);

  // 2. Resolve the L1AssetRouter address from the Bridgehub.
  const l1AssetRouterAddress: string = await bridgehub.assetRouter();
  console.log(`L1AssetRouter:  ${l1AssetRouterAddress}`);

  // 3. Resolve the L1Nullifier address from the L1AssetRouter.
  const l1AssetRouter = new ethers.Contract(l1AssetRouterAddress, L1_ASSET_ROUTER_ABI, provider);
  const l1NullifierAddress: string = await l1AssetRouter.L1_NULLIFIER();
  console.log(`L1Nullifier:    ${l1NullifierAddress}`);

  // 4. For each chain, query the deprecated L2 bridge address.
  const l1Nullifier = new ethers.Contract(l1NullifierAddress, L1_NULLIFIER_ABI, provider);
  const chains: ChainBridgeEntry[] = [];

  for (const chainId of rawChainIds) {
    const legacyBridgeAddress: string = await l1Nullifier.__DEPRECATED_l2BridgeAddress(chainId);

    if (legacyBridgeAddress !== ethers.constants.AddressZero) {
      console.log(`  chain ${chainId.toString().padEnd(12)} legacy bridge = ${legacyBridgeAddress}`);
      chains.push({ chainId: chainId.toNumber(), legacySharedBridgeAddress: legacyBridgeAddress });
    } else {
      console.log(`  chain ${chainId.toString().padEnd(12)} no legacy bridge`);
    }
  }

  if (!fs.existsSync(BRIDGE_DATA_DIR)) {
    fs.mkdirSync(BRIDGE_DATA_DIR, { recursive: true });
  }

  const outputFile = path.join(BRIDGE_DATA_DIR, `${envName}.toml`);
  fs.writeFileSync(outputFile, serializeToToml({ l1AssetRouterAddress, chains }));
  console.log(`\nSaved to: ${outputFile}`);
}

// ─── TOML serialisation ───────────────────────────────────────────────────────

// The `toml` package (v3) is parse-only and has no stringify.
function serializeToToml(data: EnvBridgeData): string {
  let out = `l1_asset_router_address = "${data.l1AssetRouterAddress}"\n`;

  for (const chain of data.chains) {
    out += "\n[[chains]]\n";
    out += `chain_id = ${chain.chainId}\n`;
    out += `legacy_shared_bridge_address = "${chain.legacySharedBridgeAddress}"\n`;
  }

  return out;
}

function parseFromToml(raw: string): EnvBridgeData {
  const parsed = toml.parse(raw);
  return {
    l1AssetRouterAddress: parsed.l1_asset_router_address,
    chains: (parsed.chains ?? []).map((c: { chain_id: number; legacy_shared_bridge_address: string }) => ({
      chainId: c.chain_id,
      legacySharedBridgeAddress: c.legacy_shared_bridge_address,
    })),
  };
}

// ─── generate command ─────────────────────────────────────────────────────────

const EMPTY_ENV_DATA: EnvBridgeData = { l1AssetRouterAddress: ethers.constants.AddressZero, chains: [] };

function generateSolidityFile(strict: boolean): void {
  const envs = ["stage", "testnet", "mainnet"] as const;
  const envData: Record<string, EnvBridgeData> = {};

  for (const env of envs) {
    const dataFile = path.join(BRIDGE_DATA_DIR, `${env}.toml`);

    if (!fs.existsSync(dataFile)) {
      const hint = `Run: yarn populate-legacy-bridge-addresses fetch --rpc <URL> --env ${env}`;
      if (strict) {
        throw new Error(`Data file not found: ${dataFile}\n${hint}`);
      }
      console.warn(`\n${"!".repeat(72)}`);
      console.warn(`!! WARNING: data file not found for env "${env}": ${dataFile}`);
      console.warn(`!! The ${env.toUpperCase()} ecosystem will be generated with an empty bridge list`);
      console.warn("!! and address(0) as the L1AssetRouter discriminator.");
      console.warn(`!! ${hint}`);
      console.warn(`${"!".repeat(72)}\n`);
      envData[env] = EMPTY_ENV_DATA;
      continue;
    }

    envData[env] = parseFromToml(fs.readFileSync(dataFile, "utf-8"));
    console.log(`Loaded ${env}: ${envData[env].chains.length} chains with legacy bridges`);
  }

  // The new Testnet ecosystem was launched after V26 and never had a legacy shared bridge,
  // so we expect no chains to have one.
  if (envData["testnet"].chains.length !== 0) {
    throw new Error(
      `Expected 0 legacy bridges for testnet, got ${envData["testnet"].chains.length}. ` +
        "The new Testnet ecosystem should not have any legacy L2SharedBridge deployments."
    );
  }

  const content = buildSolidityContent(envData["stage"], envData["testnet"], envData["mainnet"]);
  fs.writeFileSync(SOLIDITY_OUTPUT_FILE, content);
  console.log(`\nGenerated: ${SOLIDITY_OUTPUT_FILE}`);
}

// ─── Solidity code generation ─────────────────────────────────────────────────

/**
 * Emits the body of a per-ecosystem private helper function.
 * Uses `bridges` as the named return variable (already declared by the caller template).
 */
function emitHelperBody(chains: ChainBridgeEntry[], count: string, indent: string): string {
  const alloc = `${indent}bridges = new SharedBridgeOnChainId[](${count});`;
  if (chains.length === 0) return alloc;
  const assignments = chains
    .map(
      (c, i) =>
        `${indent}bridges[${i}] = SharedBridgeOnChainId({\n` +
        `${indent}    chainId: ${c.chainId},\n` +
        `${indent}    legacySharedBridgeAddress: ${c.legacySharedBridgeAddress}\n` +
        `${indent}});`
    )
    .join("\n");
  return alloc + "\n" + assignments;
}

function buildSolidityContent(stage: EnvBridgeData, testnet: EnvBridgeData, mainnet: EnvBridgeData): string {
  const stageBody = emitHelperBody(stage.chains, "STAGE_LEGACY_BRIDGES", "        ");
  const testnetBody = emitHelperBody(testnet.chains, "TESTNET_LEGACY_BRIDGES", "        ");
  const mainnetBody = emitHelperBody(mainnet.chains, "MAINNET_LEGACY_BRIDGES", "        ");

  // prettier-ignore
  return (
    "// SPDX-License-Identifier: MIT\n" +
    "\n" +
    "// This file is auto-generated by scripts/populate-legacy-shared-bridge-addresses.ts.\n" +
    "// Do not edit manually. To update, run:\n" +
    "//   yarn populate-legacy-bridge-addresses fetch --rpc <RPC_URL> --env <ENV>\n" +
    "//   yarn populate-legacy-bridge-addresses generate\n" +
    "\n" +
    "pragma solidity 0.8.28;\n" +
    "\n" +
    "import {InvalidL1AssetRouter} from \"./AssetTrackerErrors.sol\";\n" +
    "\n" +
    "/// @dev Associates a ZK chain ID with its legacy L2 shared bridge address.\n" +
    "/// @dev Chains that deployed an L2SharedBridge before the V26 upgrade are recorded here so\n" +
    "/// that GWAssetTracker can initialise legacy withdrawal support for them after the upgrade.\n" +
    "struct SharedBridgeOnChainId {\n" +
    "    /// @dev The chain ID of the ZK chain.\n" +
    "    uint256 chainId;\n" +
    "    /// @dev The address of the legacy L2SharedBridge deployed on that chain prior to V26.\n" +
    "    address legacySharedBridgeAddress;\n" +
    "}\n" +
    "\n" +
    "/// @title LegacySharedBridgeAddresses\n" +
    "/// @notice Hardcoded registry of legacy L2SharedBridge addresses for every ZK chain that\n" +
    "/// had one deployed prior to the V26 upgrade, grouped by ecosystem.\n" +
    "///\n" +
    "/// @dev Prior to V26, each ZK chain that supported ERC-20 bridging deployed its own\n" +
    "/// L2SharedBridge contract. After V26, these bridges were deprecated in favour of the\n" +
    "/// unified L2AssetRouter. This library preserves the pre-upgrade addresses so that the\n" +
    "/// GWAssetTracker can call setLegacySharedBridgeAddress() and keep legacy withdrawal\n" +
    "/// proofs valid.\n" +
    "///\n" +
    "/// @dev There are three separate ecosystems:\n" +
    "///   - Stage:   pre-production environment on Sepolia.\n" +
    "///   - Testnet: public test environment on Sepolia.\n" +
    "///   - Mainnet: production environment on Ethereum mainnet.\n" +
    "///\n" +
    "/// Because Stage and Testnet both live on Sepolia, the ecosystems are identified by\n" +
    "/// their respective L1AssetRouter addresses rather than by chain ID.\n" +
    "library LegacySharedBridgeAddresses {\n" +
    "    // ─── Chain counts ───────────────────────────────────────────────────────────\n" +
    "\n" +
    "    /// @dev Number of Stage-ecosystem chains that had a legacy L2SharedBridge.\n" +
    `    uint256 internal constant STAGE_LEGACY_BRIDGES = ${stage.chains.length};\n` +
    "\n" +
    "    /// @dev Number of Testnet-ecosystem chains that had a legacy L2SharedBridge.\n" +
    `    uint256 internal constant TESTNET_LEGACY_BRIDGES = ${testnet.chains.length};\n` +
    "\n" +
    "    /// @dev Number of Mainnet-ecosystem chains that had a legacy L2SharedBridge.\n" +
    `    uint256 internal constant MAINNET_LEGACY_BRIDGES = ${mainnet.chains.length};\n` +
    "\n" +
    "    // ─── Ecosystem discriminator addresses ──────────────────────────────────────\n" +
    "\n" +
    "    /// @dev L1AssetRouter address for the Stage ecosystem (Sepolia).\n" +
    "    /// Used to distinguish Stage from Testnet, as both are deployed on Sepolia.\n" +
    `    address internal constant STAGE_ECOSYSTEM_L1_ASSET_ROUTER_ADDRESS = ${stage.l1AssetRouterAddress};\n` +
    "\n" +
    "    /// @dev L1AssetRouter address for the Testnet ecosystem (Sepolia).\n" +
    "    /// Used to distinguish Testnet from Stage, as both are deployed on Sepolia.\n" +
    `    address internal constant TESTNET_ECOSYSTEM_L1_ASSET_ROUTER_ADDRESS = ${testnet.l1AssetRouterAddress};\n` +
    "\n" +
    "    /// @dev L1AssetRouter address for the Mainnet ecosystem (Ethereum mainnet).\n" +
    `    address internal constant MAINNET_ECOSYSTEM_L1_ASSET_ROUTER_ADDRESS = ${mainnet.l1AssetRouterAddress};\n` +
    "\n" +
    "    /// @notice Returns all (chainId, legacySharedBridgeAddress) pairs for the ecosystem\n" +
    "    /// identified by the given L1AssetRouter address.\n" +
    "    ///\n" +
    "    /// @dev The caller is the GWAssetTracker, which passes its own L1AssetRouter address so\n" +
    "    /// that this library can pick the correct list without knowing which network it is on.\n" +
    "    ///\n" +
    "    /// @param _l1AssetRouter The L1AssetRouter address of the calling ecosystem.\n" +
    "    /// @return An array of {chainId, legacySharedBridgeAddress} pairs for every chain in\n" +
    "    ///         the ecosystem that had a legacy L2SharedBridge deployed before V26.\n" +
    "    ///         Returns an empty array for ecosystems where no chains had a legacy bridge.\n" +
    "    function getLegacySharedBridgeAddressOnGateway(\n" +
    "        address _l1AssetRouter\n" +
    "    ) internal pure returns (SharedBridgeOnChainId[] memory) {\n" +
    "        if (_l1AssetRouter == STAGE_ECOSYSTEM_L1_ASSET_ROUTER_ADDRESS) {\n" +
    "            return _getStageLegacyBridges();\n" +
    "        } else if (_l1AssetRouter == TESTNET_ECOSYSTEM_L1_ASSET_ROUTER_ADDRESS) {\n" +
    "            return _getTestnetLegacyBridges();\n" +
    "        } else if (_l1AssetRouter == MAINNET_ECOSYSTEM_L1_ASSET_ROUTER_ADDRESS) {\n" +
    "            return _getMainnetLegacyBridges();\n" +
    "        }\n" +
    "        revert InvalidL1AssetRouter(_l1AssetRouter);\n" +
    "    }\n" +
    "\n" +
    "    function _getStageLegacyBridges() private pure returns (SharedBridgeOnChainId[] memory bridges) {\n" +
    stageBody + "\n" +
    "    }\n" +
    "\n" +
    "    /// @dev Testnet has no chains with legacy bridges. This function exists for consistency.\n" +
    "    function _getTestnetLegacyBridges() private pure returns (SharedBridgeOnChainId[] memory bridges) {\n" +
    testnetBody + "\n" +
    "    }\n" +
    "\n" +
    "    function _getMainnetLegacyBridges() private pure returns (SharedBridgeOnChainId[] memory bridges) {\n" +
    mainnetBody + "\n" +
    "    }\n" +
    "}\n"
  );
}

// ─── Entry point ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const program = new Command();
  program.version("0.1.0").name("populate-legacy-shared-bridge-addresses");

  program
    .command("fetch")
    .description(
      "Fetch legacy shared bridge addresses from on-chain and save to " +
        "upgrade-envs/legacy-bridge-addresses/<env>.toml"
    )
    .requiredOption("--rpc <url>", "L1 RPC URL to query")
    .requiredOption("--env <name>", "Environment name: stage | testnet | mainnet")
    .action(async (cmd) => {
      await fetchBridgeAddresses(cmd.rpc, cmd.env);
    });

  program
    .command("generate")
    .description("Regenerate LegacySharedBridgeAddresses.sol from the saved TOML data files")
    .option("--strict", "Throw if any env data file is missing instead of warning and using empty data")
    .action((cmd) => {
      generateSolidityFile(cmd.strict ?? false);
    });

  await program.parseAsync(process.argv);
}

main()
  .then(() => process.exit(0))
  .catch((err: Error) => {
    console.error("Error:", err.message);
    process.exit(1);
  });
