#!/usr/bin/env bash
#
# One canonical regeneration of every generated artifact whose input is the contract source,
# in DEPENDENCY ORDER. Each step's output feeds the next, which is why running them piecemeal
# (or in the wrong order) leaves the stale intermediate state CI then rejects:
#
#   build           -> artifacts every later step reads
#   zkstack-out     -> copied ABIs/bytecode; the anvil harness PREFERS these over out/, so a
#                      stale copy here makes the chain-state step run against the old interface
#   chain states    -> genesis deploys, so they move whenever contract bytecode moves
#   registry manifest -> pins addresses/codehashes taken from those chain states
#   selectors       -> derived from the built ABIs
#
# AllContractsHashes is deliberately NOT regenerated here: zksolc output diverges off Linux, so
# CI is the only oracle for it (dispatch the `update-hashes-on-demand` workflow instead).
#
# Usage: yarn l1 regen   (from the repo root:  yarn l1 regen)
set -euo pipefail

cd "$(dirname "$0")/.."
PORT_OFFSET="${ANVIL_INTEROP_PORT_OFFSET:-300}"

echo "==> [1/5] building l1-contracts artifacts"
forge build

echo "==> [2/5] regenerating zkstack-out"
yarn copy-to-zkstack-out

echo "==> [3/5] regenerating anvil-interop chain states (port offset ${PORT_OFFSET})"
# Mirror the state-generation job: the DA contracts are deployed too and their CREATE2 addresses
# depend on their bytecode, so they must come from the same no-metadata profile the harness builds
# l1-contracts with (setup-and-dump-state.ts sets FOUNDRY_PROFILE=anvil-interop for its own build).
(cd ../da-contracts && FOUNDRY_PROFILE=anvil-interop yarn build:foundry)
(cd test/anvil-interop && ANVIL_INTEROP_PORT_OFFSET="${PORT_OFFSET}" npx ts-node setup-and-dump-state.ts)

echo "==> [4/5] regenerating the registry manifest from the fresh chain states"
(cd test/anvil-interop && ANVIL_INTEROP_PORT_OFFSET="${PORT_OFFSET}" REGEN_REGISTRIES=1 \
    npx ts-node run-v34-to-v35-upgrade-test.ts)

echo "==> [5/5] regenerating selectors"
yarn selectors --fix

echo
echo "Done. Now run the formatting gates and commit:"
echo "  yarn lint:sol --fix --noPrompt && yarn lint:ts --fix && yarn prettier:fix   (from the repo root)"
echo "AllContractsHashes is regenerated by CI:"
echo "  gh workflow run update-hashes-on-demand.yaml --ref <branch> -f pr_number=<pr>"
