// SPDX-License-Identifier: MIT
// Generated by tools/src/bin/serialize_test_proof.rs — do not edit by hand.
pragma solidity 0.8.28;

/// @notice Fixture proof + public input for an airbender PLONK SNARK,
/// produced by `eravm-prover-host prove-snark` over the `eravm-airbender-verifier` guest.
library AirbenderPlonkProofFixture {
    function publicInputs() internal pure returns (uint256[] memory inputs) {
        inputs = new uint256[](1);
        inputs[0] = 0x00000000ec8d5e6791b56bfa33ad9eb33f63d5a53537d0527f195275f97dfc88;
    }

    function serializedProof() internal pure returns (uint256[] memory proof) {
        proof = new uint256[](44);
        proof[0] = 0x2f6f62190344240b145bce418513be162430b0c8963cddaa885068a3aed03072;
        proof[1] = 0x1559a64ac07142295e0e31868c2707e01097f3ac482705ddb5e7ccb48581587c;
        proof[2] = 0x1ce815e7a1966ab1cd32cb7cd7e889d3c6ce485ad23fbdc5541cf388e8cb6aa9;
        proof[3] = 0x06fb2a2345eb633827d62bad5bf94038ad6cf97b17a1d6039107d453afefda4c;
        proof[4] = 0x2f13da5fbeb13bcc332d1054b207b00b60162aa307f4c61a761d69496587b35a;
        proof[5] = 0x00338b7b847a685540ffd706021eb2ff5536709e777da545c42bbc97d08b3fc7;
        proof[6] = 0x058f6cb5b8ff7b27890bb843cd4c636b5213b7278f2c156c98c020c19f81ecde;
        proof[7] = 0x209f42ad3e611954cd20c5b750f4e4826e1ba34af2361d33834da4800c9acda2;
        proof[8] = 0x01ba0e4a94d31db485308d1517a4887874efe5e9e7cad64bd11a2cae3dba1838;
        proof[9] = 0x09f8d10abceb3080578366bb564f2e4fb0910d271b62f715478a642579e77573;
        proof[10] = 0x2c6239b187ff81428009e778d5248136119a68c7d2a7671b3ca6fd306f3933f7;
        proof[11] = 0x03434c6859ee8d40c21aa34aee15a4d79e56d073423c54977af752cd58c71905;
        proof[12] = 0x1a7957a2e02b3e76169f11737361e3d2bb898371445ddc1742380bd228db9683;
        proof[13] = 0x01564938b3b890fa4bdc0dd657b1f67c5824c246f950796e56a06ecd03dd9840;
        proof[14] = 0x21204e11c83f8eff9116d757ceaf579cdbf03176c88f2a45c349babb9f836859;
        proof[15] = 0x1f2c451f2c18ba5cb713527801fae182e41d45fd498239a1b98bf81777160dfe;
        proof[16] = 0x214804f1dc6f9d312fedf7dd66bd17a0df8ca18559636ef8932c2b5925a82e0a;
        proof[17] = 0x2e3d20ccf0970ba3199ef88bcb7ff265abfaf00e8409421996e0a2fe6abba872;
        proof[18] = 0x06c80968babae28ebfce08e7a1a086fa8478120c89238b65d5635b84d1591804;
        proof[19] = 0x03634c8f976a24310135aee4b1c4ec96c78e3f749e71ced3511589e4b6c563a6;
        proof[20] = 0x29cbd2b49203dc0964c406676730ef8ad586be374fe492bf55e4336c45edd66c;
        proof[21] = 0x1b53112efc6dc97e0908317d3fbe0f9f357dc62096164c1b00c7ecd2a617d687;
        proof[22] = 0x0594f5e34b3c6671cdfa129c32c43bf450418eb57d0333495cd2beb0be053782;
        proof[23] = 0x070fc10e00d98a628a8a3683573011f9d5b36a11b5bcdae980f41a2c6108ce84;
        proof[24] = 0x1ae203115326d6575c420f753d2245a9762cb115397ddd8a86a4366bac6576f2;
        proof[25] = 0x3018d9ddf8a21ac6efec68b59775c3bf66b2871c8574f52a2d9d16fc27c83da8;
        proof[26] = 0x1525a534eb8d79ff3739842d4293d8bb7d31d9c4d7bcccc897ab7ece1a846bab;
        proof[27] = 0x10e0ecb3f7fd853d4f8cf526240ca9469c2e443d6ba1388ad1d71af47f4f6652;
        proof[28] = 0x23fd3c613d53539e183b4c8b971d170a473dd8cf8a520eaf2ad997663c87fbbd;
        proof[29] = 0x19f13e92cb3701ffa85e450d0ec333242389392f35cd74c9fce03ec8838b685d;
        proof[30] = 0x2c0f716bbe2c4b71fd9065be4953a76ede5ccb5e52e441fecf8a76847de39dac;
        proof[31] = 0x2c55ec38181b8cfd329688cbbacb9c880ab10303d709564fcb00c4ab99c1fa6e;
        proof[32] = 0x2bef05c1be30d8341e060f7aaa908682700546b94c2d9fbd99771586b69b5cff;
        proof[33] = 0x204ba8b8a369ac18039e48cd8e6286a8d58d9e6cf15ce75a4d2f3ecbff8c73a9;
        proof[34] = 0x0bd45fe0df3ac7a5edb30cebbd5b25c1b796f1408a06fa9edc2dc766fe85abe9;
        proof[35] = 0x09a7259b338a3b24de977c2b58a94bb473e0d62c7998124124a5a49a2c6aa79e;
        proof[36] = 0x2c50c7dac34e67e64dcb3a513eea524265ffef8e3365c880f00aaca55381c828;
        proof[37] = 0x204f315579abd82c4fab9f5201d57983cbb11faa1c1a356a8442171e9f156e56;
        proof[38] = 0x0a1c153d99150107725821fa455237bd2ab3675de9addfee7b93483f2d962a52;
        proof[39] = 0x16422864be1da77c72ea2a54d39283d3e6024f3b85689f304b366f0d2505857b;
        proof[40] = 0x267d6ab4b106b29ed70c1c3436ccddcd9be954f9c8a7698b823b2df359eb17e8;
        proof[41] = 0x0faffcf2e7c87c446b3b1ad3678a50fdf9945d1c7a924e909273957d1f829365;
        proof[42] = 0x169aa813d4af61d83725fb166df720616ba806aabeaed3e08c8bc7d19cc4f656;
        proof[43] = 0x305e5353dfe8dd9ceec524dce23140f577cdae81a440cdcb0d589ae362b5e739;
    }
}
