//! ZiSK verifier contract generation.
//!
//! Generates `ZiskVerifier.sol` from a JSON file containing programVK and
//! rootCVadcopFinal, using a Handlebars template.
//!
//! The ZiSK SNARK uses a different proof system (snarkJS Plonk) than Airbender
//! (boojum). The inner `ZiskSnarkPlonkVerifier.sol` is auto-generated by snarkJS
//! during `ziskup setup_snark` and lives at `~/.zisk/provingKeySnark/final/PlonkVerifier.sol`.
//!
//! This module generates only the outer wrapper (`ZiskVerifier.sol`) that:
//! - Hardcodes `programVK` (ROM Merkle root of guest ELF — changes per ELF build)
//! - Hardcodes `rootCVadcopFinal` (vadcop final root — changes on SNARK circuit regen)
//! - Computes `sha256(programVK || publicValues || rootCVadcopFinal) % RFIELD`
//! - Calls the inner snarkJS PlonkVerifier for the actual SNARK check

use serde::Deserialize;
use sha3::{Digest, Keccak256};
use std::error::Error;
use std::fs;

#[derive(Deserialize)]
struct ZiskVk {
    program_vk: [u64; 4],
    root_cv_adcop_final: [u64; 4],
}

/// Generate ZiskVerifier.sol from VK JSON and template.
///
/// Optionally copies and adapts the snarkJS-generated PlonkVerifier.sol
/// (adjusting pragma and contract name for era-contracts conventions).
pub fn generate_zisk_verifier(
    vk_path: &str,
    output_path: &str,
    plonk_input_path: Option<&str>,
) -> Result<(), Box<dyn Error>> {
    let vk_json = fs::read_to_string(vk_path)?;
    let vk: ZiskVk = serde_json::from_str(&vk_json)?;

    let template = fs::read_to_string("data/zisk_verifier_contract_template.txt")?;

    // Generate programVK constants
    let program_vk_constants = format!(
        "    uint64 private constant _PROGRAM_VK_0 = {};\n\
         \x20   uint64 private constant _PROGRAM_VK_1 = {};\n\
         \x20   uint64 private constant _PROGRAM_VK_2 = {};\n\
         \x20   uint64 private constant _PROGRAM_VK_3 = {};",
        vk.program_vk[0], vk.program_vk[1], vk.program_vk[2], vk.program_vk[3],
    );

    // Generate rootCVadcopFinal constants
    let root_cv_constants = format!(
        "    uint64 private constant _ROOT_CV_ADCOP_FINAL_0 = {};\n\
         \x20   uint64 private constant _ROOT_CV_ADCOP_FINAL_1 = {};\n\
         \x20   uint64 private constant _ROOT_CV_ADCOP_FINAL_2 = {};\n\
         \x20   uint64 private constant _ROOT_CV_ADCOP_FINAL_3 = {};",
        vk.root_cv_adcop_final[0], vk.root_cv_adcop_final[1],
        vk.root_cv_adcop_final[2], vk.root_cv_adcop_final[3],
    );

    // Compute VK hash = keccak256(programVK_le_bytes || rootCVadcopFinal_le_bytes)
    let mut vk_bytes = Vec::with_capacity(64);
    for v in &vk.program_vk {
        vk_bytes.extend_from_slice(&v.to_le_bytes());
    }
    for v in &vk.root_cv_adcop_final {
        vk_bytes.extend_from_slice(&v.to_le_bytes());
    }
    let vk_hash = hex::encode(Keccak256::digest(&vk_bytes));

    // Apply template substitutions
    let contract = template
        .replace("{{program_vk_constants}}", &program_vk_constants)
        .replace("{{root_cv_constants}}", &root_cv_constants)
        .replace("{{vk_hash}}", &vk_hash);

    fs::write(output_path, &contract)?;
    println!("Generated ZiskVerifier at: {}", output_path);
    println!("  programVK: {:?}", vk.program_vk);
    println!("  rootCVadcopFinal: {:?}", vk.root_cv_adcop_final);
    println!("  VK hash: 0x{}", vk_hash);

    // Optionally copy and adapt the snarkJS PlonkVerifier
    if let Some(plonk_path) = plonk_input_path {
        let plonk_sol = fs::read_to_string(plonk_path)?;
        // Adjust pragma and contract name for era-contracts conventions
        let adapted = plonk_sol
            .replace(
                "pragma solidity >=0.7.0 <0.9.0;",
                "pragma solidity 0.8.28;",
            )
            .replace("contract PlonkVerifier", "contract ZiskSnarkPlonkVerifier");

        let plonk_output = output_path.replace("ZiskVerifier.sol", "ZiskSnarkPlonkVerifier.sol");
        fs::write(&plonk_output, &adapted)?;
        println!("Generated ZiskSnarkPlonkVerifier at: {}", plonk_output);
    }

    Ok(())
}
