/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISystemContextDeprecated,
  ISystemContextDeprecatedInterface,
} from "../../interfaces/ISystemContextDeprecated";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_blockNumber",
        type: "uint256",
      },
    ],
    name: "blockHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentBlockInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBlockNumberAndTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "blockTimestamp",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISystemContextDeprecated__factory {
  static readonly abi = _abi;
  static createInterface(): ISystemContextDeprecatedInterface {
    return new Interface(_abi) as ISystemContextDeprecatedInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISystemContextDeprecated {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISystemContextDeprecated;
  }
}
