// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from gen-registry-manifest.example.json.
// This file contains DATA ONLY; the lookup logic lives in the hand-written registry base.
// Every value is a compile-time constant: deploying the registry IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

import {CoreRegistryBase} from "contracts/upgrades/registry/CoreRegistryBase.sol";
import {CoreRegistryV99Data} from "./CoreRegistryV99Data.sol";

contract CoreRegistryV99 is CoreRegistryBase {
    function _oldProtocolVersion() internal pure override returns (uint256) {
        return CoreRegistryV99Data.OLD_PROTOCOL_VERSION;
    }

    function _newProtocolVersion() internal pure override returns (uint256) {
        return CoreRegistryV99Data.NEW_PROTOCOL_VERSION;
    }

    function _proxyAdmin() internal pure override returns (address) {
        return CoreRegistryV99Data.proxyAdmin();
    }

    function _ctmRegistry(bool _isZKsyncOS) internal pure override returns (address) {
        return CoreRegistryV99Data.ctmRegistry(_isZKsyncOS);
    }

    function _contractRows() internal pure override returns (CoreRegistryBase.EcosystemContractRow[] memory) {
        return CoreRegistryV99Data.contractRows();
    }

    function _codehashPins() internal pure override returns (CoreRegistryBase.CodehashPin[] memory) {
        return CoreRegistryV99Data.codehashPins();
    }
}
