// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from gen-registry-manifest.example.json.
// This file contains DATA ONLY; the lookup logic lives in the hand-written registry base.
// Every value is a compile-time constant: deploying the registry IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

import {CoreContract, CTMContract} from "contracts/upgrades/registry/ContractIdentifiers.sol";
import {CTMRegistryBase} from "contracts/upgrades/registry/CTMRegistryBase.sol";
import {IComplexUpgrader} from "contracts/state-transition/l2-deps/IComplexUpgrader.sol";

library ZKsyncOSCTMRegistryV99Data {
    uint256 internal constant OLD_PROTOCOL_VERSION = 420906795008; // 0.98.0
    uint256 internal constant NEW_PROTOCOL_VERSION = 425201762304; // 0.99.0

    function isZKsyncOS() internal pure returns (bool) {
        return true;
    }

    function ctmProxy() internal pure returns (address) {
        return address(uint160(0x00000000000000000000000000000000000000d001));
    }

    function ctmAddressRows() internal pure returns (CTMRegistryBase.AddressRow[] memory rows) {
        rows = new CTMRegistryBase.AddressRow[](2);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.DiamondInit,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00000000000000000000000000000000000000f204))
        }); // DiamondInit @ 0.99.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.DefaultUpgrade,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00000000000000000000000000000000000000f205))
        }); // DefaultUpgrade @ 0.99.0
        ++i;
    }

    function verifierRows() internal pure returns (CTMRegistryBase.VerifierRow[] memory rows) {
        rows = new CTMRegistryBase.VerifierRow[](1);
        rows[0] = CTMRegistryBase.VerifierRow({
            protocolVersion: NEW_PROTOCOL_VERSION,
            verifier: address(uint160(0x00000000000000000000000000000000000000e002))
        }); // verifier @ 0.99.0
    }

    function facetRows() internal pure returns (CTMRegistryBase.FacetRow[] memory rows) {
        rows = new CTMRegistryBase.FacetRow[](6);
        uint256 i = 0;
        {
            bytes4[] memory selectorList;
            selectorList = new bytes4[](2);
            selectorList[0] = bytes4(0x00000001);
            selectorList[1] = bytes4(0x00000002);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.AdminFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x00000000000000000000000000000000000000f101)),
                selectorList: selectorList
            }); // AdminFacet @ 0.98.0
            ++i;
        }
        {
            bytes4[] memory selectorList;
            selectorList = new bytes4[](1);
            selectorList[0] = bytes4(0x00000030);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.MailboxFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x00000000000000000000000000000000000000f103)),
                selectorList: selectorList
            }); // MailboxFacet @ 0.98.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.ExecutorFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                facetAddress: address(0),
                selectorList: selectorList
            }); // ExecutorFacet @ 0.98.0 (added by this upgrade)
            ++i;
        }
        {
            bytes4[] memory selectorList;
            selectorList = new bytes4[](2);
            selectorList[0] = bytes4(0x00000002);
            selectorList[1] = bytes4(0x00000003);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.AdminFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x00000000000000000000000000000000000000f201)),
                selectorList: selectorList
            }); // AdminFacet @ 0.99.0
            ++i;
        }
        {
            bytes4[] memory selectorList;
            selectorList = new bytes4[](2);
            selectorList[0] = bytes4(0x00000010);
            selectorList[1] = bytes4(0x00000011);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.GettersFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x00000000000000000000000000000000000000f102)),
                selectorList: selectorList
            }); // GettersFacet @ 0.99.0
            ++i;
        }
        {
            bytes4[] memory selectorList;
            selectorList = new bytes4[](1);
            selectorList[0] = bytes4(0x00000020);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.ExecutorFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x00000000000000000000000000000000000000f203)),
                selectorList: selectorList
            }); // ExecutorFacet @ 0.99.0
            ++i;
        }
    }

    function freezabilityRows() internal pure returns (CTMRegistryBase.FreezabilityRow[] memory rows) {
        rows = new CTMRegistryBase.FreezabilityRow[](4);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.AdminFacet, isFreezable: false}); // AdminFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.GettersFacet, isFreezable: false}); // GettersFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.MailboxFacet, isFreezable: true}); // MailboxFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.ExecutorFacet, isFreezable: true}); // ExecutorFacet
        ++i;
    }

    function l2DeploymentRows() internal pure returns (CTMRegistryBase.L2DeploymentRow[] memory rows) {
        rows = new CTMRegistryBase.L2DeploymentRow[](2);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.L2DeploymentRow({
            key: CoreContract.L2Bridgehub,
            info: IComplexUpgrader.UniversalContractUpgradeInfo({
                upgradeType: IComplexUpgrader.ContractUpgradeType.ZKsyncOSSystemProxyUpgrade,
                deployedBytecodeInfo: hex"aa01",
                newAddress: address(uint160(0x000000000000000000000000000000000000010002))
            }),
            bytecodeHash: 0x0100000000000000000000000000000000000000000000000000000000000001
        }); // L2Bridgehub
        ++i;
        rows[i] = CTMRegistryBase.L2DeploymentRow({
            key: CoreContract.L2AssetRouter,
            info: IComplexUpgrader.UniversalContractUpgradeInfo({
                upgradeType: IComplexUpgrader.ContractUpgradeType.ZKsyncOSSystemProxyUpgrade,
                deployedBytecodeInfo: hex"aa02",
                newAddress: address(uint160(0x000000000000000000000000000000000000010003))
            }),
            bytecodeHash: 0x0100000000000000000000000000000000000000000000000000000000000002
        }); // L2AssetRouter
        ++i;
    }

    function l2UpgradeDelegate() internal pure returns (address delegateTo, bytes memory delegateCalldata) {
        return (address(uint160(0x000000000000000000000000000000000000010004)), hex"beef");
    }

    function factoryDepHashes() internal pure returns (uint256[] memory hashes) {
        hashes = new uint256[](2);
        hashes[0] = uint256(0x0100000000000000000000000000000000000000000000000000000000000001);
        hashes[1] = uint256(0x0100000000000000000000000000000000000000000000000000000000000002);
    }

    function baseSystemContractHashes()
        internal
        pure
        returns (bytes32 bootloaderHash, bytes32 defaultAccountHash, bytes32 evmEmulatorHash)
    {
        return (
            0x0100000000000000000000000000000000000000000000000000000000000b00,
            0x0100000000000000000000000000000000000000000000000000000000000da0,
            0x0000000000000000000000000000000000000000000000000000000000000000
        );
    }

    function fixedForceDeploymentsData() internal pure returns (bytes memory) {
        return hex"f1f2";
    }

    function genesisParams()
        internal
        pure
        returns (
            address genesisUpgrade,
            bytes32 genesisBatchHash,
            bytes32 genesisBatchCommitment,
            uint64 genesisIndexRepeatedStorageChanges
        )
    {
        return (
            address(uint160(0x000000000000000000000000000000000000010005)),
            0x0200000000000000000000000000000000000000000000000000000000000001,
            0x0200000000000000000000000000000000000000000000000000000000000002,
            54
        );
    }

    function codehashPins() internal pure returns (CTMRegistryBase.CodehashPin[] memory pins) {
        pins = new CTMRegistryBase.CodehashPin[](0);
        uint256 i = 0;
    }
}
