// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from gen-registry-manifest.example.json.
// This file contains DATA ONLY; the lookup logic lives in the hand-written registry base.
// Every value is a compile-time constant: deploying the registry IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

import {CTMRegistryBase} from "contracts/upgrades/registry/CTMRegistryBase.sol";
import {ZKsyncOSCTMRegistryV99Data} from "./ZKsyncOSCTMRegistryV99Data.sol";

contract ZKsyncOSCTMRegistryV99 is CTMRegistryBase {
    function _isZKsyncOS() internal pure override returns (bool) {
        return ZKsyncOSCTMRegistryV99Data.isZKsyncOS();
    }

    function _oldProtocolVersion() internal pure override returns (uint256) {
        return ZKsyncOSCTMRegistryV99Data.OLD_PROTOCOL_VERSION;
    }

    function _newProtocolVersion() internal pure override returns (uint256) {
        return ZKsyncOSCTMRegistryV99Data.NEW_PROTOCOL_VERSION;
    }

    function _ctmProxy() internal pure override returns (address) {
        return ZKsyncOSCTMRegistryV99Data.ctmProxy();
    }

    function _ctmAddressRows() internal pure override returns (CTMRegistryBase.AddressRow[] memory) {
        return ZKsyncOSCTMRegistryV99Data.ctmAddressRows();
    }

    function _verifierRows() internal pure override returns (CTMRegistryBase.AddressRow[] memory) {
        return ZKsyncOSCTMRegistryV99Data.verifierRows();
    }

    function _facetRows() internal pure override returns (CTMRegistryBase.FacetRow[] memory) {
        return ZKsyncOSCTMRegistryV99Data.facetRows();
    }

    function _freezabilityRows() internal pure override returns (CTMRegistryBase.FreezabilityRow[] memory) {
        return ZKsyncOSCTMRegistryV99Data.freezabilityRows();
    }

    function _l2DeploymentRows() internal pure override returns (CTMRegistryBase.L2DeploymentRow[] memory) {
        return ZKsyncOSCTMRegistryV99Data.l2DeploymentRows();
    }

    function _l2UpgradeDelegate() internal pure override returns (address, bytes memory) {
        return ZKsyncOSCTMRegistryV99Data.l2UpgradeDelegate();
    }

    function _factoryDepHashes() internal pure override returns (uint256[] memory) {
        return ZKsyncOSCTMRegistryV99Data.factoryDepHashes();
    }

    function _baseSystemContractHashes() internal pure override returns (bytes32, bytes32, bytes32) {
        return ZKsyncOSCTMRegistryV99Data.baseSystemContractHashes();
    }

    function _fixedForceDeploymentsData() internal pure override returns (bytes memory) {
        return ZKsyncOSCTMRegistryV99Data.fixedForceDeploymentsData();
    }

    function _chainCreationInitCalldata() internal pure override returns (bytes memory) {
        return ZKsyncOSCTMRegistryV99Data.chainCreationInitCalldata();
    }

    function _genesisParams() internal pure override returns (address, bytes32, bytes32, uint64) {
        return ZKsyncOSCTMRegistryV99Data.genesisParams();
    }

    function _codehashPins() internal pure override returns (CTMRegistryBase.CodehashPin[] memory) {
        return ZKsyncOSCTMRegistryV99Data.codehashPins();
    }
}
