/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockKnownCodesStorageInterface extends Interface {
  getFunction(
    nameOrSignature: "getMarker" | "markBytecodeAsPublished"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MockBytecodePublished"): EventFragment;

  encodeFunctionData(
    functionFragment: "getMarker",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markBytecodeAsPublished",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "getMarker", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markBytecodeAsPublished",
    data: BytesLike
  ): Result;
}

export namespace MockBytecodePublishedEvent {
  export type InputTuple = [bytecodeHash: BytesLike];
  export type OutputTuple = [bytecodeHash: string];
  export interface OutputObject {
    bytecodeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockKnownCodesStorage extends BaseContract {
  connect(runner?: ContractRunner | null): MockKnownCodesStorage;
  waitForDeployment(): Promise<this>;

  interface: MockKnownCodesStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMarker: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  markBytecodeAsPublished: TypedContractMethod<
    [_bytecodeHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMarker"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "markBytecodeAsPublished"
  ): TypedContractMethod<[_bytecodeHash: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "MockBytecodePublished"
  ): TypedContractEvent<
    MockBytecodePublishedEvent.InputTuple,
    MockBytecodePublishedEvent.OutputTuple,
    MockBytecodePublishedEvent.OutputObject
  >;

  filters: {
    "MockBytecodePublished(bytes32)": TypedContractEvent<
      MockBytecodePublishedEvent.InputTuple,
      MockBytecodePublishedEvent.OutputTuple,
      MockBytecodePublishedEvent.OutputObject
    >;
    MockBytecodePublished: TypedContractEvent<
      MockBytecodePublishedEvent.InputTuple,
      MockBytecodePublishedEvent.OutputTuple,
      MockBytecodePublishedEvent.OutputObject
    >;
  };
}
