/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockL1MessengerInterface extends Interface {
  getFunction(
    nameOrSignature: "requestBytecodeL1Publication" | "sendToL1"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MockBytecodeL1Published"): EventFragment;

  encodeFunctionData(
    functionFragment: "requestBytecodeL1Publication",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "sendToL1", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "requestBytecodeL1Publication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendToL1", data: BytesLike): Result;
}

export namespace MockBytecodeL1PublishedEvent {
  export type InputTuple = [bytecodeHash: BytesLike];
  export type OutputTuple = [bytecodeHash: string];
  export interface OutputObject {
    bytecodeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockL1Messenger extends BaseContract {
  connect(runner?: ContractRunner | null): MockL1Messenger;
  waitForDeployment(): Promise<this>;

  interface: MockL1MessengerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  requestBytecodeL1Publication: TypedContractMethod<
    [_bytecodeHash: BytesLike],
    [void],
    "nonpayable"
  >;

  sendToL1: TypedContractMethod<[arg0: BytesLike], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "requestBytecodeL1Publication"
  ): TypedContractMethod<[_bytecodeHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendToL1"
  ): TypedContractMethod<[arg0: BytesLike], [string], "nonpayable">;

  getEvent(
    key: "MockBytecodeL1Published"
  ): TypedContractEvent<
    MockBytecodeL1PublishedEvent.InputTuple,
    MockBytecodeL1PublishedEvent.OutputTuple,
    MockBytecodeL1PublishedEvent.OutputObject
  >;

  filters: {
    "MockBytecodeL1Published(bytes32)": TypedContractEvent<
      MockBytecodeL1PublishedEvent.InputTuple,
      MockBytecodeL1PublishedEvent.OutputTuple,
      MockBytecodeL1PublishedEvent.OutputObject
    >;
    MockBytecodeL1Published: TypedContractEvent<
      MockBytecodeL1PublishedEvent.InputTuple,
      MockBytecodeL1PublishedEvent.OutputTuple,
      MockBytecodeL1PublishedEvent.OutputObject
    >;
  };
}
