import * as fs from "fs";
import * as path from "path";

const DEFAULT_ANVIL_CONFIG_PATH = path.resolve(__dirname, "../../config/anvil-config.json");
const STATE_VERSION_PATTERN = /^v\d+\.\d+\.\d+$/;

/**
 * A chain-states folder name from `config/anvil-config.json`, validated as `v<major>.<minor>.<patch>` (so it
 * cannot name a path outside `chain-states/`):
 * - `stateVersion`: this branch's chain states, generated by `setup-and-dump-state.ts` from the current contracts.
 * - `upgradeSourceStateVersion`: the previous release's chain states, which `run-upgrade-test.ts` upgrades with
 *   the release's default upgrade. A release bump moves it to the outgoing `stateVersion`.
 */
export function readStateVersion(
  key: "stateVersion" | "upgradeSourceStateVersion",
  configPath: string = DEFAULT_ANVIL_CONFIG_PATH
): string {
  const cfg = JSON.parse(fs.readFileSync(configPath, "utf-8")) as Record<string, unknown>;
  const value = cfg[key];
  if (typeof value !== "string" || !STATE_VERSION_PATTERN.test(value)) {
    throw new Error(`${key} in ${configPath} must match v<major>.<minor>.<patch>`);
  }
  return value;
}
