import * as fs from "fs";
import * as path from "path";

const anvilConfigPath = path.resolve(__dirname, "../../config/anvil-config.json");
const STATE_VERSION_PATTERN = /^v\d+\.\d+\.\d+$/;

/**
 * Fixture selection from `config/anvil-config.json`:
 * - `stateVersion`: this branch's chain states, generated by `setup-and-dump-state.ts` from the current contracts.
 * - `upgradeSourceStateVersion`: the previous release's chain states, which `run-upgrade-test.ts` upgrades with
 *   the release's default upgrade. A release bump moves it to the outgoing `stateVersion`.
 */
export function readAnvilConfig(): { stateVersion: string; upgradeSourceStateVersion: string } {
  const cfg = JSON.parse(fs.readFileSync(anvilConfigPath, "utf-8")) as {
    stateVersion?: string;
    upgradeSourceStateVersion?: string;
  };
  for (const key of ["stateVersion", "upgradeSourceStateVersion"] as const) {
    if (!cfg[key] || !STATE_VERSION_PATTERN.test(cfg[key]!)) {
      throw new Error(`${key} in ${anvilConfigPath} must match v<major>.<minor>.<patch>`);
    }
  }
  return { stateVersion: cfg.stateVersion!, upgradeSourceStateVersion: cfg.upgradeSourceStateVersion! };
}
