use std::time::{SystemTime, UNIX_EPOCH};

use serde::Serialize;
use serde_json::{json, Value};

use crate::common::forge::{all_runs_cast_transactions, ForgeRunner};
use crate::common::logger;

/// Current output format version.
pub const OUTPUT_VERSION: u32 = 1;

/// Standard envelope for all protocol_ops command `--out` JSON.
///
/// Includes flat **`transactions`** (`to` / `data` / `value`) for
/// `chain execute-simulated-transactions` / `ExecuteProtocolOpsOut.s.sol`.
#[derive(Serialize)]
pub struct CommandEnvelope {
    pub command: String,
    pub version: u32,
    pub runs: Vec<RunEntry>,
    pub transactions: Vec<Value>,
    pub input: Value,
    pub output: Value,
}

/// A single forge script execution record.
#[derive(Serialize)]
pub struct RunEntry {
    pub script: String,
    pub run: Value,
}

impl CommandEnvelope {
    pub fn new<I: Serialize, O: Serialize>(
        command: &str,
        runner: &ForgeRunner,
        input: &I,
        output: &O,
    ) -> anyhow::Result<Self> {
        let runs = runner
            .runs()
            .iter()
            .map(|r| RunEntry {
                script: r.script.display().to_string(),
                run: r.payload.clone(),
            })
            .collect();
        let transactions = all_runs_cast_transactions(runner);

        Ok(Self {
            command: command.to_string(),
            version: OUTPUT_VERSION,
            runs,
            transactions,
            input: serde_json::to_value(input)?,
            output: serde_json::to_value(output)?,
        })
    }

    pub fn write_to_file(&self, path: &std::path::Path) -> anyhow::Result<()> {
        if let Some(parent) = path.parent() {
            if !parent.exists() {
                std::fs::create_dir_all(parent).map_err(|e| {
                    anyhow::anyhow!(
                        "Failed to create output directory '{}': {e}",
                        parent.display()
                    )
                })?;
            }
        }
        let json = serde_json::to_string_pretty(self)?;
        std::fs::write(path, &json).map_err(|e| {
            anyhow::anyhow!("Failed to write output file '{}': {e}", path.display())
        })?;
        Ok(())
    }
}

/// Fetch the L1 chain ID from the given RPC URL.
async fn fetch_l1_chain_id(l1_rpc_url: &str) -> anyhow::Result<u64> {
    use ethers::providers::{Http, Middleware, Provider};
    let provider = Provider::<Http>::try_from(l1_rpc_url)?;
    let chain_id = provider.get_chainid().await?;
    Ok(chain_id.as_u64())
}

/// Write `--out` JSON file if the user requested it. No-op otherwise.
pub async fn write_output_if_requested<I, O>(
    command: &str,
    shared: &crate::common::SharedRunArgs,
    runner: &ForgeRunner,
    input: &I,
    output: &O,
) -> anyhow::Result<()>
where
    I: Serialize,
    O: Serialize,
{
    if shared.out_path.is_some() || shared.safe_transactions_out.is_some() {
        let envelope = CommandEnvelope::new(command, runner, input, output)?;
        if let Some(ref out_path) = shared.out_path {
            envelope.write_to_file(out_path)?;
            logger::info(format!("Full output written to: {}", out_path.display()));
        }
        if let Some(ref safe_path) = shared.safe_transactions_out {
            let l1_chain_id = fetch_l1_chain_id(&shared.l1_rpc_url).await?;
            write_safe_transactions(command, &envelope.transactions, l1_chain_id, safe_path)?;
            logger::info(format!(
                "Safe transactions written to: {}",
                safe_path.display()
            ));
        }
    }
    Ok(())
}

/// Write transactions in Gnosis Safe Transaction Builder JSON format.
fn write_safe_transactions(
    command: &str,
    transactions: &[Value],
    l1_chain_id: u64,
    path: &std::path::Path,
) -> anyhow::Result<()> {
    let created_at = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();

    let safe_txs: Vec<Value> = transactions
        .iter()
        .map(|tx| {
            json!({
                "to": tx.get("to").and_then(|v| v.as_str()).unwrap_or(""),
                "value": tx.get("value").and_then(|v| v.as_str()).unwrap_or("0"),
                "data": tx.get("data").and_then(|v| v.as_str()).unwrap_or("0x"),
                "contractMethod": null,
                "contractInputsValues": null,
            })
        })
        .collect();

    let envelope = json!({
        "version": "1.0",
        "chainId": l1_chain_id.to_string(),
        "createdAt": created_at,
        "meta": {
            "name": command,
            "description": format!("Transactions generated by protocol_ops: {command}"),
        },
        "transactions": safe_txs,
    });

    if let Some(parent) = path.parent() {
        if !parent.exists() {
            std::fs::create_dir_all(parent)?;
        }
    }
    let json = serde_json::to_string_pretty(&envelope)?;
    std::fs::write(path, &json)
        .map_err(|e| anyhow::anyhow!("Failed to write safe transactions to '{}': {e}", path.display()))?;
    Ok(())
}
