[permanent_contracts]
create2_factory_addr = "0x4e59b44847b379578588920cA78FbF26c0B4956C"
# this salt can be changed from run to run to. Todo: move this to input of script.
create2_factory_salt = "0x0000000000000000000000000000000000000000000000000000000000000000"

[core_contracts]
bridgehub_proxy_addr = "0x236D1c3Ff32Bd0Ca26b72Af287E895627c0478cE"

[ctm_contracts]
ctm_proxy_addr = "0x8b448ac7cd0f18F3d8464E2645575772a26A3b6b"
l1_bytecodes_supplier_addr = "0x662B8fE285BB3aab483e75Ec46136e01aaa154f9"
rollup_da_manager = "0x064ac968CCad1948fceE025fD59c20b153c88072"

# Legacy Gateway configuration for settlement layer validation
# This section contains historical data about chains that settled on the legacy Gateway
[legacy_gateway]
# The chain ID of the legacy Gateway (9075 for mainnet)
chain_id = 123

[[legacy_gateway.chain_intervals]]
chain_id = 270
migrate_to_sl_batch = 657297
migrate_from_sl_batch = 661306
sl_batch_lower_bound = 117
sl_batch_upper_bound = 1818
[[legacy_gateway.chain_intervals]]
chain_id = 270
migrate_to_sl_batch = 661504
migrate_from_sl_batch = 665934
sl_batch_lower_bound = 1828
sl_batch_upper_bound = 7195
[[legacy_gateway.chain_intervals]]
chain_id = 270
migrate_to_sl_batch = 665948
migrate_from_sl_batch = 666082
sl_batch_lower_bound = 7203
sl_batch_upper_bound = 7460
[[legacy_gateway.chain_intervals]]
chain_id = 6475
migrate_to_sl_batch = 5591
migrate_from_sl_batch = 10038
sl_batch_lower_bound = 4677
sl_batch_upper_bound = 25245
[[legacy_gateway.chain_intervals]]
chain_id = 499
migrate_to_sl_batch = 1775
migrate_from_sl_batch = 53871
sl_batch_lower_bound = 2918
sl_batch_upper_bound = 25494
[[legacy_gateway.chain_intervals]]
chain_id = 37111
migrate_to_sl_batch = 7371
migrate_from_sl_batch = 8416
sl_batch_lower_bound = 8663
sl_batch_upper_bound = 26620
