name: Restore artifacts cache
description: Restore the contract artifacts cache saved by build-contract-artifacts.yaml
inputs:
  key:
    description: "Cache key to restore"
    required: true
runs:
  using: composite
  steps:
    - name: Restore artifacts cache
      uses: actions/cache/restore@v3
      with:
        fail-on-cache-miss: true
        key: ${{ inputs.key }}
        path: |
          da-contracts/cache-forge
          da-contracts/out
          l1-contracts/cache-forge
          l1-contracts/out
          l1-contracts/zkout
          l2-contracts/cache-forge
          l2-contracts/zkout
          system-contracts/zkout
