// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {DefaultCoreUpgrade} from "../default-upgrade/DefaultCoreUpgrade.s.sol";

/// @notice Prepares the v35 upgrade. Generated by `yarn new-release` as the plain {DefaultCoreUpgrade}; the
/// release's own preparation overrides its hooks here.
// solhint-disable-next-line contract-name-capwords
contract CoreUpgrade_v35 is DefaultCoreUpgrade {}
