// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

/// @title snarkJS Plonk verifier interface
/// @author Matter Labs
/// @custom:security-contact security@matterlabs.dev
/// @notice ABI of a snarkJS-generated Plonk verifier contract.
/// @dev The implementation is machine-generated by snarkJS from the
///      circuit's verification key and changes whenever the circuit is
///      regenerated, so it is deployed as a standalone contract and
///      referenced by address. See `verifiers/README.md` for how to
///      generate, deploy and wire the implementation.
interface ISnarkPlonkVerifier {
    /// @notice Verify a snarkJS Plonk proof against its public signals.
    function verifyProof(uint256[24] calldata _proof, uint256[1] calldata _pubSignals) external view returns (bool);
}
