// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

/// @title ZiSK snarkJS Plonk verifier interface
/// @author Matter Labs
/// @custom:security-contact security@matterlabs.dev
/// @notice ABI of the snarkJS-generated Plonk verifier for the ZiSK
///         vadcop-final wrap. It serves the ZiSK lane alone: the Airbender
///         lane reaches its own Plonk verifier through `IVerifier`.
/// @dev The implementation is machine-generated by snarkJS from the ZiSK SNARK
///      setup's verification key and changes whenever that circuit is
///      regenerated, so it is deployed as a standalone contract named
///      `ZiskSnarkPlonkVerifier` and referenced by address. See
///      `verifiers/README.md` for how to generate, deploy and wire it.
interface IZiskSnarkPlonkVerifier {
    /// @notice Verify a ZiSK snarkJS Plonk proof against its public signal.
    function verifyProof(uint256[24] calldata _proof, uint256[1] calldata _pubSignals) external view returns (bool);
}
