//! Full prepare flow: canonical [`UpgradeInner::prepare`] plus the
//! governance-ownership precondition needed for governance-owned proxies and
//! the operational-admin ServerNotifier upgrade step.
//!
//! Only the prepare phase has orchestration that warrants its own struct.
//! The governance phase is pure replay (read TOMLs, dispatch
//! `governanceExecuteCalls`) and lives as a free helper in
//! [`super::upgrade`].

use std::{fs, path::Path};

use alloy::hex;
use alloy::primitives::Bytes;
use anyhow::Context;
use serde::Deserialize;

use crate::common::abi::AdminFunctionsAbi;
use crate::common::env_config::OwnableProxyEntry;
use crate::common::forge::ForgeRunner;
use crate::common::logger;
use crate::common::wallets::Wallet;

use super::upgrade_inner::{CtmPrepareEntry, PrepareInputs, PrepareOutput, UpgradeInner};

pub struct UpgradeFull<'a> {
    inner: UpgradeInner<'a>,
    /// Registry of contract owners that need ownership-transfer calls wrapped
    /// (see `OwnerWrap` in `IAdminFunctions.sol`). Empty for envs where every
    /// current owner is already an EOA.
    ownable_proxies: Vec<OwnableProxyEntry>,
}

impl<'a> UpgradeFull<'a> {
    pub fn new(inner: UpgradeInner<'a>) -> Self {
        Self {
            inner,
            ownable_proxies: Vec::new(),
        }
    }

    pub fn with_ownable_proxies(mut self, proxies: Vec<OwnableProxyEntry>) -> Self {
        self.ownable_proxies = proxies;
        self
    }

    /// Run the prepare phase: `ensureCtmsAndProxyAdminsOwnedByGovernance` as
    /// a precondition, then `inner.prepare`, then the CTM admin calls that are
    /// intentionally outside governance ownership (currently ServerNotifier).
    /// All steps broadcast against the supplied runner so every deployer/owner
    /// tx goes into the prepare Safe-bundle set.
    pub async fn prepare(
        &self,
        runner: &mut ForgeRunner,
        deployer: &Wallet,
        inputs: &PrepareInputs,
    ) -> anyhow::Result<PrepareOutput> {
        self.run_pre_steps(runner, deployer).await?;
        let prepared = self.inner.prepare(runner, deployer, inputs).await?;
        self.run_ctm_admin_steps(runner, deployer, &prepared.ctm_tomls)?;
        Ok(prepared)
    }

    /// Pre-step hook: ensure governance owns each registered CTM + ProxyAdmin
    /// before the prepare deploys run. The downstream stage-1 governance
    /// calls (e.g. CTM ProxyAdmin upgradeAndCall) assume governance ownership;
    /// this is a no-op when ownership is already correct. Operational surfaces
    /// such as ServerNotifier are upgraded separately without transferring
    /// their ProxyAdmins to governance.
    ///
    /// The outer call has no permission gating — the deployer signs it. Inner
    /// `vm.startBroadcast(<owner>)` blocks emit the actual `transferOwnership`
    /// txs as the appropriate EOA owner; those land in that EOA's Safe bundle
    /// when the harness emits per-sender bundles. Contract owners listed in
    /// the env's `[[ownable_proxies]]` registry are routed through their
    /// wrapping shape (legacy Governance: `scheduleTransparent`+`executeInstant`,
    /// OZ ChainAdmin: `multicall`); contract owners *not* registered cause a
    /// hard revert.
    async fn run_pre_steps(
        &self,
        runner: &mut ForgeRunner,
        deployer: &Wallet,
    ) -> anyhow::Result<()> {
        let governance = crate::common::l1_contracts::resolve_governance(
            &runner.rpc_url,
            self.inner.bridgehub(),
        )
        .await?;
        let wraps = encode_owner_wraps(&self.ownable_proxies);
        runner.run(
            runner
                .script_call(
                    AdminFunctionsAbi::ensureCtmsAndProxyAdminsOwnedByGovernanceWithWrapsCall {
                        _bridgehub: self.inner.bridgehub(),
                        _governance: governance,
                        _wraps: wraps,
                    },
                )
                .with_wallet(deployer),
        )?;
        Ok(())
    }

    /// Execute the per-CTM admin calls generated by `CTMUpgrade_v33`. These
    /// calls target ownable operational admin surfaces whose ownership is
    /// intentionally preserved; `AdminFunctions` resolves each call target's
    /// current owner and routes through the configured owner wrapper when the
    /// owner is itself a contract.
    fn run_ctm_admin_steps(
        &self,
        runner: &mut ForgeRunner,
        deployer: &Wallet,
        ctm_entries: &[CtmPrepareEntry],
    ) -> anyhow::Result<()> {
        let wraps = encode_owner_wraps(&self.ownable_proxies);
        for entry in ctm_entries {
            let encoded_calls_hex = read_server_notifier_upgrade_calls(&entry.toml)?;
            let encoded_calls = hex::decode(encoded_calls_hex.trim_start_matches("0x"))
                .with_context(|| {
                    format!("invalid CTM admin calls hex in {}", entry.toml.display())
                })?;
            logger::step(format!("Running CTM admin calls for {:#x}", entry.proxy));
            runner.run(
                runner
                    .script_call(AdminFunctionsAbi::executeOwnableCallsWithWrapsCall {
                        _callsToExecute: Bytes::from(encoded_calls),
                        _wraps: wraps.clone(),
                    })
                    .with_gas_limit(crate::common::forge::DEFAULT_SCRIPT_GAS_LIMIT)
                    .with_wallet(deployer),
            )?;
        }
        Ok(())
    }
}

fn encode_owner_wraps(entries: &[OwnableProxyEntry]) -> Vec<AdminFunctionsAbi::OwnerWrap> {
    entries
        .iter()
        .map(|e| AdminFunctionsAbi::OwnerWrap {
            ownableContract: e.addr,
            kind: e.kind.to_solidity_u8(),
        })
        .collect()
}

#[derive(Debug, Deserialize)]
struct CtmAdminCallsToml {
    ctm_admin_calls: CtmAdminCalls,
}

#[derive(Debug, Deserialize)]
struct CtmAdminCalls {
    server_notifier_upgrade: String,
}

fn read_server_notifier_upgrade_calls(path: &Path) -> anyhow::Result<String> {
    let raw = fs::read_to_string(path).with_context(|| format!("read {}", path.display()))?;
    let parsed: CtmAdminCallsToml =
        toml::from_str(&raw).with_context(|| format!("parse {}", path.display()))?;
    Ok(parsed.ctm_admin_calls.server_notifier_upgrade)
}
