// SPDX-License-Identifier: MIT

pragma solidity ^0.8.21;

// 0x0fef9068
error ClaimFailedDepositFailed();
// 0x066f53b1
error EmptyToken();
// 0x1c55230b
error NativeTokenVaultAlreadySet();
// 0x7ec6d3a1
error OnlyFailureStatusAllowed();
// 0x84204265
error TokenAlreadyInBridgedTokensList();
// 0xb4aeddbc
error WrongCounterpart();
// 0x636c90db
error WrongL2Sender(address providedL2Sender);
// 0x61cdb17e
error WrongMsgLength(uint256 expected, uint256 length);
// selector regenerated by `yarn selectors --fix`
error InteropWithdrawalWrongDestination();
// selector regenerated by `yarn selectors --fix`
error InteropWithdrawalNotSingleCall();
// selector regenerated by `yarn selectors --fix`
error InteropWithdrawalWrongTarget();
// selector regenerated by `yarn selectors --fix`
error InteropWithdrawalWrongOrigin();
