/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type ImmutableDataStruct = { index: BigNumberish; value: BytesLike };

export type ImmutableDataStructOutput = [index: bigint, value: string] & {
  index: bigint;
  value: string;
};

export interface IImmutableSimulatorInterface extends Interface {
  getFunction(
    nameOrSignature: "getImmutable" | "setImmutables"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getImmutable",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setImmutables",
    values: [AddressLike, ImmutableDataStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getImmutable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImmutables",
    data: BytesLike
  ): Result;
}

export interface IImmutableSimulator extends BaseContract {
  connect(runner?: ContractRunner | null): IImmutableSimulator;
  waitForDeployment(): Promise<this>;

  interface: IImmutableSimulatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getImmutable: TypedContractMethod<
    [_dest: AddressLike, _index: BigNumberish],
    [string],
    "view"
  >;

  setImmutables: TypedContractMethod<
    [_dest: AddressLike, _immutables: ImmutableDataStruct[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getImmutable"
  ): TypedContractMethod<
    [_dest: AddressLike, _index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "setImmutables"
  ): TypedContractMethod<
    [_dest: AddressLike, _immutables: ImmutableDataStruct[]],
    [void],
    "nonpayable"
  >;

  filters: {};
}
