additional_addresses_for_minting = []

[tokens.DAI]
name = "DAI"
symbol = "DAI"
decimals = 18
implementation = "TestnetERC20Token.sol"
mint = "10000000000"

[tokens.USDC]
name = "USDC"
symbol = "USDC"
decimals = 18
implementation = "TestnetERC20Token.sol"
mint = "10000000000"
