// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from v32-local.json.
// This file contains DATA ONLY; the lookup logic lives in the hand-written registry base.
// Every value is a compile-time constant: deploying the registry IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

import {EcosystemContract} from "contracts/upgrades/registry/ContractIdentifiers.sol";
import {CoreRegistryBase} from "contracts/upgrades/registry/CoreRegistryBase.sol";

library CoreRegistryV32Data {
    uint256 internal constant OLD_PROTOCOL_VERSION = 133143986176; // 0.31.0
    uint256 internal constant NEW_PROTOCOL_VERSION = 137438953472; // 0.32.0

    function proxyAdmin() internal pure returns (address) {
        return address(uint160(0x000fa38b5c8cb180809e0c95e2ee923ec093123285));
    }

    function ctmRegistry(bool _isZKsyncOS) internal pure returns (address) {
        return
            _isZKsyncOS
                ? address(uint160(0x000000000000000000000000000000000000000000))
                : address(uint160(0x000000000000000000000000000000000000000000));
    }

    function contractRows() internal pure returns (CoreRegistryBase.EcosystemContractRow[] memory rows) {
        rows = new CoreRegistryBase.EcosystemContractRow[](1);
        uint256 i = 0;
        rows[i] = CoreRegistryBase.EcosystemContractRow({
            key: EcosystemContract.MessageRoot,
            proxy: address(uint160(0x004a02a75c31b433fc8d87f510500b90e0fa7e0254)),
            implOld: address(uint160(0x0036529ce3fd7a08a689b0c707325b3f5034570eca)),
            implNew: address(uint160(0x00821f3361d454cc98b7555221a06be563a7e2e0a6))
        }); // MessageRoot
        ++i;
    }

    function codehashPins() internal pure returns (CoreRegistryBase.CodehashPin[] memory pins) {
        pins = new CoreRegistryBase.CodehashPin[](1);
        uint256 i = 0;
        pins[i] = CoreRegistryBase.CodehashPin({
            target: address(uint160(0x00821f3361d454cc98b7555221a06be563a7e2e0a6)),
            expectedCodehash: 0x38a76dd3fa4cc1b89fd4fb2add08c18b50a7187c8f229f129a78af31070ccaa4
        }); // MessageRoot implNew
        ++i;
    }
}
