// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from v32-local.json.
// Every value below is a compile-time constant: deploying this contract IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

import {ICTMRegistry} from "contracts/upgrades/registry/ICTMRegistry.sol";
import {CoreContract} from "contracts/upgrades/registry/ContractIdentifiers.sol";

import {CTMContract} from "contracts/upgrades/registry/ContractIdentifiers.sol";
import {IComplexUpgrader} from "contracts/state-transition/l2-deps/IComplexUpgrader.sol";

contract ZKsyncOSCTMRegistryV32 is ICTMRegistry {
    uint256 internal constant OLD_PROTOCOL_VERSION = 133143986176; // 0.31.0
    uint256 internal constant NEW_PROTOCOL_VERSION = 137438953472; // 0.32.0

    error RegistryUnknownKey();

    function isZKsyncOS() external pure returns (bool) {
        return true;
    }

    function oldProtocolVersion() external pure returns (uint256) {
        return OLD_PROTOCOL_VERSION;
    }

    function newProtocolVersion() external pure returns (uint256) {
        return NEW_PROTOCOL_VERSION;
    }

    function ctmProxy() external pure returns (address) {
        return address(uint160(0x00a7ef69a0644e7c3b24bcbe6bf2bf75662e851bf8));
    }

    function ctmAddress(CTMContract _contract, uint256 _protocolVersion) external pure returns (address) {
        if (_contract == CTMContract.AdminFacet && _protocolVersion == OLD_PROTOCOL_VERSION)
            return address(uint160(0x00bb27525459cfa6650f9491808ecf1fee6434b236));
        if (_contract == CTMContract.AdminFacet && _protocolVersion == NEW_PROTOCOL_VERSION)
            return address(uint160(0x00045857bdeae7c1c7252d611eb24eb55564198b4c));
        if (_contract == CTMContract.DefaultUpgrade && _protocolVersion == NEW_PROTOCOL_VERSION)
            return address(uint160(0x002b5a4e5493d4a54e717057b127cf0c000c876f9b));
        if (_contract == CTMContract.DiamondInit && _protocolVersion == NEW_PROTOCOL_VERSION)
            return address(uint160(0x00413b1afca96a3df5a686d8bfbf93d30688a7f7d9));
        if (_protocolVersion == OLD_PROTOCOL_VERSION || _protocolVersion == NEW_PROTOCOL_VERSION) return address(0);
        revert RegistryUnknownKey();
    }

    function verifier(uint256 _protocolVersion) external pure returns (address) {
        if (_protocolVersion == OLD_PROTOCOL_VERSION)
            return address(uint160(0x005422b0509a532dd24b0dd99afac766e66172af37));
        if (_protocolVersion == NEW_PROTOCOL_VERSION)
            return address(uint160(0x0002df3a3f960393f5b349e40a599feda91a7cc1a7));
        revert RegistryUnknownKey();
    }

    function facetList(uint256 _protocolVersion) external pure returns (CTMContract[] memory list) {
        if (_protocolVersion == OLD_PROTOCOL_VERSION) {
            list = new CTMContract[](1);
            list[0] = CTMContract.AdminFacet;
            return list;
        }
        if (_protocolVersion == NEW_PROTOCOL_VERSION) {
            list = new CTMContract[](1);
            list[0] = CTMContract.AdminFacet;
            return list;
        }
        revert RegistryUnknownKey();
    }

    function facetSelectors(
        CTMContract _facet,
        uint256 _protocolVersion
    ) external pure returns (bytes4[] memory selectors) {
        if (_facet == CTMContract.AdminFacet && _protocolVersion == OLD_PROTOCOL_VERSION) {
            selectors = new bytes4[](24);
            selectors[0] = bytes4(0x054e80a3);
            selectors[1] = bytes4(0x0e18b681);
            selectors[2] = bytes4(0x17338945);
            selectors[3] = bytes4(0xf9afb97e);
            selectors[4] = bytes4(0x1b48b94a);
            selectors[5] = bytes4(0x1cc5d103);
            selectors[6] = bytes4(0x21f603d7);
            selectors[7] = bytes4(0x235d9eb5);
            selectors[8] = bytes4(0x23b31192);
            selectors[9] = bytes4(0x2765d079);
            selectors[10] = bytes4(0x27ae4c16);
            selectors[11] = bytes4(0x2878fe74);
            selectors[12] = bytes4(0x3b6d7534);
            selectors[13] = bytes4(0x4623c91d);
            selectors[14] = bytes4(0x4dd18bf5);
            selectors[15] = bytes4(0x5b898748);
            selectors[16] = bytes4(0x60eae0e7);
            selectors[17] = bytes4(0x64bf8d66);
            selectors[18] = bytes4(0x6e762e98);
            selectors[19] = bytes4(0xa9f6d941);
            selectors[20] = bytes4(0xb4fcb577);
            selectors[21] = bytes4(0xbe6f11cf);
            selectors[22] = bytes4(0xc5f1f1f5);
            selectors[23] = bytes4(0xe76db865);
            return selectors;
        }
        if (_facet == CTMContract.AdminFacet && _protocolVersion == NEW_PROTOCOL_VERSION) {
            selectors = new bytes4[](24);
            selectors[0] = bytes4(0x054e80a3);
            selectors[1] = bytes4(0x0e18b681);
            selectors[2] = bytes4(0x17338945);
            selectors[3] = bytes4(0xf9afb97e);
            selectors[4] = bytes4(0x1b48b94a);
            selectors[5] = bytes4(0x1cc5d103);
            selectors[6] = bytes4(0x21f603d7);
            selectors[7] = bytes4(0x235d9eb5);
            selectors[8] = bytes4(0x23b31192);
            selectors[9] = bytes4(0x2765d079);
            selectors[10] = bytes4(0x27ae4c16);
            selectors[11] = bytes4(0x2878fe74);
            selectors[12] = bytes4(0x3b6d7534);
            selectors[13] = bytes4(0x4623c91d);
            selectors[14] = bytes4(0x4dd18bf5);
            selectors[15] = bytes4(0x5b898748);
            selectors[16] = bytes4(0x60eae0e7);
            selectors[17] = bytes4(0x64bf8d66);
            selectors[18] = bytes4(0x6e762e98);
            selectors[19] = bytes4(0xa9f6d941);
            selectors[20] = bytes4(0xb4fcb577);
            selectors[21] = bytes4(0xbe6f11cf);
            selectors[22] = bytes4(0xc5f1f1f5);
            selectors[23] = bytes4(0xe76db865);
            return selectors;
        }
        revert RegistryUnknownKey();
    }

    function facetIsFreezable(CTMContract _facet) external pure returns (bool) {
        if (_facet == CTMContract.AdminFacet) return false;
        revert RegistryUnknownKey();
    }

    function l2ForceDeployList(uint256 _protocolVersion) external pure returns (CoreContract[] memory list) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        list = new CoreContract[](1);
        list[0] = CoreContract.L2V31Upgrade;
    }

    function l2ForceDeployment(
        CoreContract _contract,
        uint256 _protocolVersion
    ) external pure returns (IComplexUpgrader.UniversalContractUpgradeInfo memory) {
        if (_contract == CoreContract.L2V31Upgrade && _protocolVersion == NEW_PROTOCOL_VERSION) {
            return
                IComplexUpgrader.UniversalContractUpgradeInfo({
                    upgradeType: IComplexUpgrader.ContractUpgradeType.ZKsyncOSUnsafeForceDeployment,
                    deployedBytecodeInfo: hex"d8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce30000000000000000000000000000000000000000000000000000000000000006d8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce3",
                    newAddress: address(uint160(0x0000000000000000000000000000000000000ab001))
                });
        }
        revert RegistryUnknownKey();
    }

    function l2BytecodeHash(CoreContract _contract, uint256 _protocolVersion) external pure returns (bytes32) {
        if (_contract == CoreContract.L2V31Upgrade && _protocolVersion == NEW_PROTOCOL_VERSION)
            return 0xd8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce3;
        if (_protocolVersion == OLD_PROTOCOL_VERSION || _protocolVersion == NEW_PROTOCOL_VERSION) return bytes32(0);
        revert RegistryUnknownKey();
    }

    function l2UpgradeDelegate(
        uint256 _protocolVersion
    ) external pure returns (address delegateTo, bytes memory delegateCalldata) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return (address(uint160(0x0000000000000000000000000000000000000ab001)), hex"");
    }

    function factoryDepHashes(uint256 _protocolVersion) external pure returns (uint256[] memory hashes) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        hashes = new uint256[](0);
    }

    function baseSystemContractHashes(
        uint256 _protocolVersion
    ) external pure returns (bytes32 bootloaderHash, bytes32 defaultAccountHash, bytes32 evmEmulatorHash) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return (
            0x0000000000000000000000000000000000000000000000000000000000000000,
            0x0000000000000000000000000000000000000000000000000000000000000000,
            0x0000000000000000000000000000000000000000000000000000000000000000
        );
    }

    function fixedForceDeploymentsData(uint256 _protocolVersion) external pure returns (bytes memory) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return hex"f1f2";
    }

    function chainCreationInitCalldata(uint256 _protocolVersion) external pure returns (bytes memory) {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return hex"c1c2";
    }

    function genesisParams(
        uint256 _protocolVersion
    )
        external
        pure
        returns (
            address genesisUpgrade,
            bytes32 genesisBatchHash,
            bytes32 genesisBatchCommitment,
            uint64 genesisIndexRepeatedStorageChanges
        )
    {
        if (_protocolVersion != NEW_PROTOCOL_VERSION) revert RegistryUnknownKey();
        return (
            address(uint160(0x00cb41110b0bd637a219021f0c5aa416bccb4ff100)),
            0x0000000000000000000000000000000000000000000000000000000000000001,
            0x0000000000000000000000000000000000000000000000000000000000000001,
            54
        );
    }

    function verifyAll() external view returns (bool) {
        if (
            address(uint160(0x00045857bdeae7c1c7252d611eb24eb55564198b4c)).codehash !=
            0xe8e31854a39f59042ebdf56730808bd85eabdff0c2a16bd8e67afbccb7425836
        ) return false;
        if (
            address(uint160(0x002b5a4e5493d4a54e717057b127cf0c000c876f9b)).codehash !=
            0x615b7fee27d5819c81ad8dad8e000bf8c663ac10aa772345d8792527a8dc6fe7
        ) return false;
        if (
            address(uint160(0x00413b1afca96a3df5a686d8bfbf93d30688a7f7d9)).codehash !=
            0x3f62a808c81d674b4d985a0d617f95fe4cda74674182b9137e5119e147cc8045
        ) return false;
        return true;
    }
}
