// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from v32-local.json.
// This file contains DATA ONLY; the lookup logic lives in the hand-written registry base.
// Every value is a compile-time constant: deploying the registry IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

import {CoreContract, CTMContract} from "contracts/upgrades/registry/ContractIdentifiers.sol";
import {CTMRegistryBase} from "contracts/upgrades/registry/CTMRegistryBase.sol";
import {IComplexUpgrader} from "contracts/state-transition/l2-deps/IComplexUpgrader.sol";

library ZKsyncOSCTMRegistryV32Data {
    uint256 internal constant OLD_PROTOCOL_VERSION = 133143986176; // 0.31.0
    uint256 internal constant NEW_PROTOCOL_VERSION = 137438953472; // 0.32.0

    function isZKsyncOS() internal pure returns (bool) {
        return true;
    }

    function ctmProxy() internal pure returns (address) {
        return address(uint160(0x002ed7fa601037fc1a7f295aee9b4adf79fe8ccf6d));
    }

    function ctmAddressRows() internal pure returns (CTMRegistryBase.AddressRow[] memory rows) {
        rows = new CTMRegistryBase.AddressRow[](2);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.DefaultUpgrade,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00dde78e6202518ff4936b5302cc2891ec180e8bff))
        }); // DefaultUpgrade @ 0.32.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.DiamondInit,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00b06c856c8eabd1d8321b687e188204c1018bc4e5))
        }); // DiamondInit @ 0.32.0
        ++i;
    }

    function verifierRows() internal pure returns (CTMRegistryBase.VerifierRow[] memory rows) {
        rows = new CTMRegistryBase.VerifierRow[](1);
        rows[0] = CTMRegistryBase.VerifierRow({
            protocolVersion: NEW_PROTOCOL_VERSION,
            verifier: address(uint160(0x00ab7b4c595d3ce8c85e16da86630f2fc223b05057))
        }); // verifier @ 0.32.0
    }

    function facetRows() internal pure returns (CTMRegistryBase.FacetRow[] memory rows) {
        rows = new CTMRegistryBase.FacetRow[](11);
        uint256 i = 0;
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.AdminFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x001834220ad2494f02d62e5a66a8ebbf92e47caa09)),
                selectorList: selectorList
            }); // AdminFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.GettersFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x0008caebad34fc471dda5dce669a2eb1d3deeab945)),
                selectorList: selectorList
            }); // GettersFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.ExecutorFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x00860bd61cd9206a6492b6947342c19e045c353510)),
                selectorList: selectorList
            }); // ExecutorFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.MigratorFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x007c413eaaf1ac4fc0cd39d44c307b9a20985416f9)),
                selectorList: selectorList
            }); // MigratorFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.CommitterFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x006baa73ed8dbea5ef75193d005b91a0b5bdf8add1)),
                selectorList: selectorList
            }); // CommitterFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.AdminFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x00aca81583840b1bf2ddf6cde824ada250c1936b4d)),
                selectorList: selectorList
            }); // AdminFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.GettersFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x0070bda08dbe07363968e9ee53d899dfe48560605b)),
                selectorList: selectorList
            }); // GettersFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.ExecutorFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x0026b862f640357268bd2d9e95bc81553a2aa81d7e)),
                selectorList: selectorList
            }); // ExecutorFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.MigratorFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x00a56f946d6398dd7d9d4d9b337cf9e0f68982ca5b)),
                selectorList: selectorList
            }); // MigratorFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.CommitterFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x005d42ebdbba61412295d7b0302d6f50ac449ddb4f)),
                selectorList: selectorList
            }); // CommitterFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.MailboxFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                facetAddress: address(uint160(0x007154413e65c9715dfbdca2f1bc7ad5d0bbed539f)),
                selectorList: selectorList
            }); // MailboxFacet @ 0.32.0
            ++i;
        }
    }

    function freezabilityRows() internal pure returns (CTMRegistryBase.FreezabilityRow[] memory rows) {
        rows = new CTMRegistryBase.FreezabilityRow[](6);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.AdminFacet, isFreezable: false}); // AdminFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.GettersFacet, isFreezable: false}); // GettersFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.MailboxFacet, isFreezable: true}); // MailboxFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.ExecutorFacet, isFreezable: true}); // ExecutorFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.MigratorFacet, isFreezable: false}); // MigratorFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.CommitterFacet, isFreezable: true}); // CommitterFacet
        ++i;
    }

    function l2DeploymentRows() internal pure returns (CTMRegistryBase.L2DeploymentRow[] memory rows) {
        rows = new CTMRegistryBase.L2DeploymentRow[](1);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.L2DeploymentRow({
            key: CoreContract.L2V31Upgrade,
            info: IComplexUpgrader.UniversalContractUpgradeInfo({
                upgradeType: IComplexUpgrader.ContractUpgradeType.ZKsyncOSUnsafeForceDeployment,
                deployedBytecodeInfo: hex"d8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce30000000000000000000000000000000000000000000000000000000000000006d8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce3",
                newAddress: address(uint160(0x0000000000000000000000000000000000000ab001))
            }),
            bytecodeHash: 0xd8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce3
        }); // L2V31Upgrade
        ++i;
    }

    function l2UpgradeDelegate() internal pure returns (address delegateTo, bytes memory delegateCalldata) {
        return (address(uint160(0x0000000000000000000000000000000000000ab001)), hex"");
    }

    function factoryDepHashes() internal pure returns (uint256[] memory hashes) {
        hashes = new uint256[](0);
    }

    function baseSystemContractHashes()
        internal
        pure
        returns (bytes32 bootloaderHash, bytes32 defaultAccountHash, bytes32 evmEmulatorHash)
    {
        return (
            0x0000000000000000000000000000000000000000000000000000000000000000,
            0x0000000000000000000000000000000000000000000000000000000000000000,
            0x0000000000000000000000000000000000000000000000000000000000000000
        );
    }

    function fixedForceDeploymentsData() internal pure returns (bytes memory) {
        return hex"f1f2";
    }

    function genesisParams()
        internal
        pure
        returns (
            address genesisUpgrade,
            bytes32 genesisBatchHash,
            bytes32 genesisBatchCommitment,
            uint64 genesisIndexRepeatedStorageChanges
        )
    {
        return (
            address(uint160(0x00da2f0cc90fdb3a22f1e517ba7aaab926eb125344)),
            0x0000000000000000000000000000000000000000000000000000000000000001,
            0x0000000000000000000000000000000000000000000000000000000000000001,
            54
        );
    }

    function codehashPins() internal pure returns (CTMRegistryBase.CodehashPin[] memory pins) {
        pins = new CTMRegistryBase.CodehashPin[](8);
        uint256 i = 0;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00dde78e6202518ff4936b5302cc2891ec180e8bff)),
            expectedCodehash: 0x5faf1d86a01c82bee946ad7c5ec15ced0660650a4778dae50f4c5a0cc056a1d9
        }); // DefaultUpgrade @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00b06c856c8eabd1d8321b687e188204c1018bc4e5)),
            expectedCodehash: 0x1c11c008864151015433b20dd022626e5f271bc21db03693c82be87aaac46f6b
        }); // DiamondInit @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00aca81583840b1bf2ddf6cde824ada250c1936b4d)),
            expectedCodehash: 0xe8e31854a39f59042ebdf56730808bd85eabdff0c2a16bd8e67afbccb7425836
        }); // AdminFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x0070bda08dbe07363968e9ee53d899dfe48560605b)),
            expectedCodehash: 0x6eb8cfdb1a91fd28763e291cfe354d2bedbd8cbf7bbc01b1c30b60329c4f33f5
        }); // GettersFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x0026b862f640357268bd2d9e95bc81553a2aa81d7e)),
            expectedCodehash: 0x44eafc4ee037764abdaf3c51b011ad76b212bed96171391036b5fa825b16674e
        }); // ExecutorFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00a56f946d6398dd7d9d4d9b337cf9e0f68982ca5b)),
            expectedCodehash: 0x0cb6b357a2495ebad9edbde1e8aed66c507e5c57376b1ca0c10fe06907be1305
        }); // MigratorFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x005d42ebdbba61412295d7b0302d6f50ac449ddb4f)),
            expectedCodehash: 0xd4c360992416dd82f883f8e7eb3fb160326825598f56f93ded25035e2b63bfd9
        }); // CommitterFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x007154413e65c9715dfbdca2f1bc7ad5d0bbed539f)),
            expectedCodehash: 0x7097bc045e3c90a9c6f7bc485d69e95582eb40c41a5762b66c99d4d3024c5da0
        }); // MailboxFacet @ 0.32.0
        ++i;
    }
}
