// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from v32-local.json.
// This file contains DATA ONLY; the lookup logic lives in the hand-written registry base.
// Every value is a compile-time constant: deploying the registry IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

import {CTMRegistryBase} from "contracts/upgrades/registry/CTMRegistryBase.sol";
import {ZKsyncOSCTMRegistryV32Data} from "./ZKsyncOSCTMRegistryV32Data.sol";

contract ZKsyncOSCTMRegistryV32 is CTMRegistryBase {
    function _isZKsyncOS() internal pure override returns (bool) {
        return ZKsyncOSCTMRegistryV32Data.isZKsyncOS();
    }

    function _oldProtocolVersion() internal pure override returns (uint256) {
        return ZKsyncOSCTMRegistryV32Data.OLD_PROTOCOL_VERSION;
    }

    function _newProtocolVersion() internal pure override returns (uint256) {
        return ZKsyncOSCTMRegistryV32Data.NEW_PROTOCOL_VERSION;
    }

    function _ctmProxy() internal pure override returns (address) {
        return ZKsyncOSCTMRegistryV32Data.ctmProxy();
    }

    function _ctmAddressRows() internal pure override returns (CTMRegistryBase.AddressRow[] memory) {
        return ZKsyncOSCTMRegistryV32Data.ctmAddressRows();
    }

    function _verifierRows() internal pure override returns (CTMRegistryBase.VerifierRow[] memory) {
        return ZKsyncOSCTMRegistryV32Data.verifierRows();
    }

    function _facetRows() internal pure override returns (CTMRegistryBase.FacetRow[] memory) {
        return ZKsyncOSCTMRegistryV32Data.facetRows();
    }

    function _freezabilityRows() internal pure override returns (CTMRegistryBase.FreezabilityRow[] memory) {
        return ZKsyncOSCTMRegistryV32Data.freezabilityRows();
    }

    function _l2DeploymentRows() internal pure override returns (CTMRegistryBase.L2DeploymentRow[] memory) {
        return ZKsyncOSCTMRegistryV32Data.l2DeploymentRows();
    }

    // slither-disable-next-line unused-return
    function _l2UpgradeDelegate() internal pure override returns (address, bytes memory) {
        return ZKsyncOSCTMRegistryV32Data.l2UpgradeDelegate();
    }

    function _factoryDepHashes() internal pure override returns (uint256[] memory) {
        return ZKsyncOSCTMRegistryV32Data.factoryDepHashes();
    }

    // slither-disable-next-line unused-return
    function _baseSystemContractHashes() internal pure override returns (bytes32, bytes32, bytes32) {
        return ZKsyncOSCTMRegistryV32Data.baseSystemContractHashes();
    }

    function _fixedForceDeploymentsData() internal pure override returns (bytes memory) {
        return ZKsyncOSCTMRegistryV32Data.fixedForceDeploymentsData();
    }

    // slither-disable-next-line unused-return
    function _genesisParams() internal pure override returns (address, bytes32, bytes32, uint64) {
        return ZKsyncOSCTMRegistryV32Data.genesisParams();
    }

    function _codehashPins() internal pure override returns (CTMRegistryBase.CodehashPin[] memory) {
        return ZKsyncOSCTMRegistryV32Data.codehashPins();
    }
}
