// SPDX-License-Identifier: MIT

pragma solidity 0.8.28;

// !!! GENERATED FILE — DO NOT EDIT !!!
// Generated by scripts/gen-registry.ts from v32-local.json.
// This file contains DATA ONLY; the lookup logic lives in the hand-written registry base.
// Every value is a compile-time constant: deploying the registry IS the commitment.
// Reproduce by re-running the generator on the audited manifest and diffing this source.

import {CoreContract, CTMContract} from "contracts/upgrades/registry/ContractIdentifiers.sol";
import {CTMRegistryBase} from "contracts/upgrades/registry/CTMRegistryBase.sol";
import {IComplexUpgrader} from "contracts/state-transition/l2-deps/IComplexUpgrader.sol";

library ZKsyncOSCTMRegistryV32Data {
    uint256 internal constant OLD_PROTOCOL_VERSION = 133143986176; // 0.31.0
    uint256 internal constant NEW_PROTOCOL_VERSION = 137438953472; // 0.32.0

    function isZKsyncOS() internal pure returns (bool) {
        return true;
    }

    function ctmProxy() internal pure returns (address) {
        return address(uint160(0x009b8fa6c5da55af7887cc97eccc7d788659475193));
    }

    function ctmAddressRows() internal pure returns (CTMRegistryBase.AddressRow[] memory rows) {
        rows = new CTMRegistryBase.AddressRow[](14);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.AdminFacet,
            protocolVersion: OLD_PROTOCOL_VERSION,
            value: address(uint160(0x001834220ad2494f02d62e5a66a8ebbf92e47caa09))
        }); // AdminFacet @ 0.31.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.AdminFacet,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00045857bdeae7c1c7252d611eb24eb55564198b4c))
        }); // AdminFacet @ 0.32.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.DefaultUpgrade,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x002b5a4e5493d4a54e717057b127cf0c000c876f9b))
        }); // DefaultUpgrade @ 0.32.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.DiamondInit,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00413b1afca96a3df5a686d8bfbf93d30688a7f7d9))
        }); // DiamondInit @ 0.32.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.GettersFacet,
            protocolVersion: OLD_PROTOCOL_VERSION,
            value: address(uint160(0x0008caebad34fc471dda5dce669a2eb1d3deeab945))
        }); // GettersFacet @ 0.31.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.GettersFacet,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x0008caebad34fc471dda5dce669a2eb1d3deeab945))
        }); // GettersFacet @ 0.32.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.MailboxFacet,
            protocolVersion: OLD_PROTOCOL_VERSION,
            value: address(uint160(0x00cf8f444a5bf4f7de2e2bc572c5ba90245b2d3d89))
        }); // MailboxFacet @ 0.31.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.MailboxFacet,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00cf8f444a5bf4f7de2e2bc572c5ba90245b2d3d89))
        }); // MailboxFacet @ 0.32.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.ExecutorFacet,
            protocolVersion: OLD_PROTOCOL_VERSION,
            value: address(uint160(0x00d94e56e0c17bd1e0eb67ca231996079bae2f7a9a))
        }); // ExecutorFacet @ 0.31.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.ExecutorFacet,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00d94e56e0c17bd1e0eb67ca231996079bae2f7a9a))
        }); // ExecutorFacet @ 0.32.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.MigratorFacet,
            protocolVersion: OLD_PROTOCOL_VERSION,
            value: address(uint160(0x001f3278a574430d5b79a7b8d507eb7126ba2c584d))
        }); // MigratorFacet @ 0.31.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.MigratorFacet,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x001f3278a574430d5b79a7b8d507eb7126ba2c584d))
        }); // MigratorFacet @ 0.32.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.CommitterFacet,
            protocolVersion: OLD_PROTOCOL_VERSION,
            value: address(uint160(0x00353fc44dfe46c4ada74a563f89923a65350c5741))
        }); // CommitterFacet @ 0.31.0
        ++i;
        rows[i] = CTMRegistryBase.AddressRow({
            key: CTMContract.CommitterFacet,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x00353fc44dfe46c4ada74a563f89923a65350c5741))
        }); // CommitterFacet @ 0.32.0
        ++i;
    }

    /// @dev `AddressRow.key` is unused for verifier rows (set to the first enum variant).
    function verifierRows() internal pure returns (CTMRegistryBase.AddressRow[] memory rows) {
        rows = new CTMRegistryBase.AddressRow[](2);
        rows[0] = CTMRegistryBase.AddressRow({
            key: CTMContract.AdminFacet,
            protocolVersion: OLD_PROTOCOL_VERSION,
            value: address(uint160(0x005422b0509a532dd24b0dd99afac766e66172af37))
        }); // verifier @ 0.31.0
        rows[1] = CTMRegistryBase.AddressRow({
            key: CTMContract.AdminFacet,
            protocolVersion: NEW_PROTOCOL_VERSION,
            value: address(uint160(0x0002df3a3f960393f5b349e40a599feda91a7cc1a7))
        }); // verifier @ 0.32.0
    }

    function facetRows() internal pure returns (CTMRegistryBase.FacetRow[] memory rows) {
        rows = new CTMRegistryBase.FacetRow[](12);
        uint256 i = 0;
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.AdminFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // AdminFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.GettersFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // GettersFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.MailboxFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // MailboxFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.ExecutorFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // ExecutorFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.MigratorFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // MigratorFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.CommitterFacet,
                protocolVersion: OLD_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // CommitterFacet @ 0.31.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.AdminFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // AdminFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.GettersFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // GettersFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.MailboxFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // MailboxFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.ExecutorFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // ExecutorFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.MigratorFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // MigratorFacet @ 0.32.0
            ++i;
        }
        {
            // No pinned selector list: the facet self-describes (ISelfDescribingFacet.selectors()).
            bytes4[] memory selectorList = new bytes4[](0);
            rows[i] = CTMRegistryBase.FacetRow({
                facet: CTMContract.CommitterFacet,
                protocolVersion: NEW_PROTOCOL_VERSION,
                selectorList: selectorList
            }); // CommitterFacet @ 0.32.0
            ++i;
        }
    }

    function freezabilityRows() internal pure returns (CTMRegistryBase.FreezabilityRow[] memory rows) {
        rows = new CTMRegistryBase.FreezabilityRow[](6);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.AdminFacet, isFreezable: false}); // AdminFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.GettersFacet, isFreezable: false}); // GettersFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.MailboxFacet, isFreezable: true}); // MailboxFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.ExecutorFacet, isFreezable: true}); // ExecutorFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.MigratorFacet, isFreezable: false}); // MigratorFacet
        ++i;
        rows[i] = CTMRegistryBase.FreezabilityRow({facet: CTMContract.CommitterFacet, isFreezable: true}); // CommitterFacet
        ++i;
    }

    function l2DeploymentRows() internal pure returns (CTMRegistryBase.L2DeploymentRow[] memory rows) {
        rows = new CTMRegistryBase.L2DeploymentRow[](1);
        uint256 i = 0;
        rows[i] = CTMRegistryBase.L2DeploymentRow({
            key: CoreContract.L2V31Upgrade,
            info: IComplexUpgrader.UniversalContractUpgradeInfo({
                upgradeType: IComplexUpgrader.ContractUpgradeType.ZKsyncOSUnsafeForceDeployment,
                deployedBytecodeInfo: hex"d8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce30000000000000000000000000000000000000000000000000000000000000006d8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce3",
                newAddress: address(uint160(0x0000000000000000000000000000000000000ab001))
            }),
            bytecodeHash: 0xd8ceeb1af16ce49c7c068d8b9bcbca8a80f978611cb4ec0a1c08a95b0295dce3
        }); // L2V31Upgrade
        ++i;
    }

    function l2UpgradeDelegate() internal pure returns (address delegateTo, bytes memory delegateCalldata) {
        return (address(uint160(0x0000000000000000000000000000000000000ab001)), hex"");
    }

    function factoryDepHashes() internal pure returns (uint256[] memory hashes) {
        hashes = new uint256[](0);
    }

    function baseSystemContractHashes()
        internal
        pure
        returns (bytes32 bootloaderHash, bytes32 defaultAccountHash, bytes32 evmEmulatorHash)
    {
        return (
            0x0000000000000000000000000000000000000000000000000000000000000000,
            0x0000000000000000000000000000000000000000000000000000000000000000,
            0x0000000000000000000000000000000000000000000000000000000000000000
        );
    }

    function fixedForceDeploymentsData() internal pure returns (bytes memory) {
        return hex"f1f2";
    }

    function chainCreationInitCalldata() internal pure returns (bytes memory) {
        return hex"c1c2";
    }

    function genesisParams()
        internal
        pure
        returns (
            address genesisUpgrade,
            bytes32 genesisBatchHash,
            bytes32 genesisBatchCommitment,
            uint64 genesisIndexRepeatedStorageChanges
        )
    {
        return (
            address(uint160(0x00cb41110b0bd637a219021f0c5aa416bccb4ff100)),
            0x0000000000000000000000000000000000000000000000000000000000000001,
            0x0000000000000000000000000000000000000000000000000000000000000001,
            54
        );
    }

    function codehashPins() internal pure returns (CTMRegistryBase.CodehashPin[] memory pins) {
        pins = new CTMRegistryBase.CodehashPin[](8);
        uint256 i = 0;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00045857bdeae7c1c7252d611eb24eb55564198b4c)),
            expectedCodehash: 0xe8e31854a39f59042ebdf56730808bd85eabdff0c2a16bd8e67afbccb7425836
        }); // AdminFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x002b5a4e5493d4a54e717057b127cf0c000c876f9b)),
            expectedCodehash: 0x615b7fee27d5819c81ad8dad8e000bf8c663ac10aa772345d8792527a8dc6fe7
        }); // DefaultUpgrade @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00413b1afca96a3df5a686d8bfbf93d30688a7f7d9)),
            expectedCodehash: 0x3f62a808c81d674b4d985a0d617f95fe4cda74674182b9137e5119e147cc8045
        }); // DiamondInit @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x0008caebad34fc471dda5dce669a2eb1d3deeab945)),
            expectedCodehash: 0x6eb8cfdb1a91fd28763e291cfe354d2bedbd8cbf7bbc01b1c30b60329c4f33f5
        }); // GettersFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00cf8f444a5bf4f7de2e2bc572c5ba90245b2d3d89)),
            expectedCodehash: 0x5b57e0c10904fb14593ff53e21abe0767c32b6842756dafa7ea76dbf2a22ff58
        }); // MailboxFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00d94e56e0c17bd1e0eb67ca231996079bae2f7a9a)),
            expectedCodehash: 0x941916e9669e766aedaf2f02c36405ab1a12393c8d7badd54607ca300a9048aa
        }); // ExecutorFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x001f3278a574430d5b79a7b8d507eb7126ba2c584d)),
            expectedCodehash: 0xb46bf0e9faf014f7ae48b518a854de07f262a5f7cfdcd4bc51404f56e0b87e2e
        }); // MigratorFacet @ 0.32.0
        ++i;
        pins[i] = CTMRegistryBase.CodehashPin({
            target: address(uint160(0x00353fc44dfe46c4ada74a563f89923a65350c5741)),
            expectedCodehash: 0xa528dfec9924d790b1a385a90a7313c3fcfa70f1916af8791d772a9950b55d6f
        }); // CommitterFacet @ 0.32.0
        ++i;
    }
}
