[profile.default]
src = "contracts-preprocessed"
out = "out"
libs = ["lib"]
cache_path = "cache-forge"
evm_version = "paris"
remappings = [
    "@openzeppelin/contracts-v4/=lib/openzeppelin-contracts-v4/contracts/",
    "@openzeppelin/contracts-upgradeable-v4/=lib/openzeppelin-contracts-upgradeable-v4/contracts/",
]
solc_version = "0.8.24"

[profile.default.zksync]
zksolc = "1.5.7"
enable_eravm_extensions = true
suppressed_errors = ["sendtransfer"]
