[profile.default]
src = "contracts-preprocessed"
out = "out"
libs = ["lib"]
cache_path = "cache-forge"
evm_version = "cancun"
solc_version = "0.8.24"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
suppressedErrors = ["sendtransfer"]

[profile.default.zksync]
zksolc = "1.5.6"
suppressedErrors = ["sendtransfer"]
