[profile.default]
src = "contracts-preprocessed"
out = "out"
libs = ["lib"]
cache_path = "cache-forge"
evm_version = "paris"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
optimizer = true
optimizer_runs = 9999999

[profile.default.zksync]
zksolc = "1.5.0"
enable_eravm_extensions = true
optimizer = true
optimizer_runs = 9999999
