[profile.default]
src = "contracts-preprocessed"
out = "out"
libs = ["lib"]
cache_path = "cache-forge"
evm_version = "cancun"
solc_version = "0.8.28"
remappings = [
    "@openzeppelin/contracts-v4/=lib/openzeppelin-contracts-v4/contracts/",
    "@openzeppelin/contracts-upgradeable-v4/=lib/openzeppelin-contracts-upgradeable-v4/contracts/",
]

[profile.default.zksync]
zksolc = "1.5.11"
enable_eravm_extensions = true
optimization = "0"
suppressed_errors = ["sendtransfer"]
