name: Build and release

on:
  push:
    branches:
      - "*"

jobs:
  build-contracts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
          cache: yarn

      - name: Init
        id: init
        run: |
          yarn
          echo "release_tag=$(echo ${GITHUB_REF#refs/heads/})-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build contracts
        run: |
          yarn l1 build
          yarn l2 build
          yarn sc build

      - name: Prepare artifacts
        run: |
          tar -czvf l1-contracts.tar.gz ./l1-contracts
          tar -czvf l2-contracts.tar.gz ./l2-contracts
          tar -czvf system-contracts.tar.gz ./system-contracts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.init.outputs.release_tag }}
          fail_on_unmatched_files: true
          body: ""
          files: |
            l1-contracts.tar.gz
            l2-contracts.tar.gz
            system-contracts.tar.gz
