# A Github action that uses codespell and typos to check spell.
# .codespell/.codespellrc is the config file of codespell.
# .codespell/wordlist.txt is a list of words that will ignore word checks.
# More details please check the following link:
# https://github.com/codespell-project/codespell
#
# _typos.toml is a config file of typos.
# More details about typos is https://github.com/crate-ci/typos

name: Codespell

on: pull_request

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install prerequisites
        run: sudo pip install -r ./.codespell/requirements.txt

      - name: Spell check
        run: codespell --config=./.codespell/.codespellrc

  typos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@master
