name: Invariant Tests

on:
  schedule:
    - cron: "00 01 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.branches.outputs.branches }}
    steps:
      - name: Define branches
        id: branches
        run: |
          if [[ ${{ github.event_name }} == "schedule" ]]; then
            echo 'branches=["main", "dev"]' >> "$GITHUB_OUTPUT"
          else
            echo "branches=[\"$GITHUB_REF\"]" >> "$GITHUB_OUTPUT"
          fi

  test:
    needs: define-matrix
    strategy:
      matrix:
        branch: ${{ fromJSON(needs.define-matrix.outputs.branches) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ matrix.branch }}

      - name: Install Foundry
        uses: ./.github/actions/install-foundry
        with:
          role: build

      - name: Show forge version
        shell: bash
        run: forge --version

      - name: Cache yarn packages
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install yarn packages
        shell: bash
        run: yarn

      - name: Run tests
        run: |
          cd l1-contracts
          yarn test:invariant:l1-context
