name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint:check

      - name: Lint errors
        run: yarn l1 errors-lint --check

  # TODO: fix codespell CI
  # codespell:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout the repository
  #       uses: actions/checkout@v6

  #     - name: pip cache
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  #         restore-keys: ${{ runner.os }}-pip-

  #     - name: Install prerequisites
  #       run: sudo pip install -r ./.codespell/requirements.txt

  #     - name: Spell check
  #       run: codespell --config=./.codespell/.codespellrc

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check for typos
        uses: crate-ci/typos@master
