name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint:check

      - name: Lint errors
        run: yarn l1 errors-lint --check

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2

  protocol-ops-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --check
        working-directory: protocol-ops

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check for typos
        uses: crate-ci/typos@master
